#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require 'json'
# JSON.pretty_generate(object)

require 'fileutils'
# FileUtils.mkpath '/a/b/c'
# FileUtils.cp(src, dst)
# FileUtils.mv 'oldname', 'newname'
# FileUtils.rm(path_to_image)
# FileUtils.rm_rf('dir/to/remove')

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/LucilleCore.rb"

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/KeyValueStore.rb"
=begin
    KeyValueStore::setFlagTrue(repositorylocation or nil, key)
    KeyValueStore::setFlagFalse(repositorylocation or nil, key)
    KeyValueStore::flagIsTrue(repositorylocation or nil, key)

    KeyValueStore::set(repositorylocation or nil, key, value)
    KeyValueStore::getOrNull(repositorylocation or nil, key)
    KeyValueStore::getOrDefaultValue(repositorylocation or nil, key, defaultValue)
    KeyValueStore::destroy(repositorylocation or nil, key)
=end

# --------------------------------------------------------------------

require_relative "Projects.rb"

# -----------------------------------------------------------------------------

def projectuuidIsValid(projectuuid)
    return false if projectuuid.nil?
    !Projects::getProjectByUUIDOrNUll(projectuuid).nil?
end

def itemuuidIsValid(projectuuid, itemuuid)
    return false if projectuuid.nil?
    !Projects::getProjectByUUIDOrNUll(projectuuid).nil?
end

def processing_done(projectuuid, itemuuid)
    Projects::detachItemFromProject(projectuuid, itemuuid)
    
    timespan = Runner::stop(itemuuid)
    exit if timespan.nil?
    
    timespan = [timespan, 3600*2].min # To avoid problems after leaving things running
    puts "Sending #{timespan} seconds to project #{projectuuid}"
    Ping::ping(projectuuid, timespan, Projects::pingRetainPeriodInSeconds())

    puts "Sending #{timespan} seconds to item #{itemuuid}"
    Ping::ping(itemuuid, timespan, Projects::pingRetainPeriodInSeconds())

end

def processing_recast(projectuuid, itemuuid)
    timespan = Runner::stop(itemuuid)
    if timespan then
        timespan = [timespan, 3600*2].min # To avoid problems after leaving things running
        puts "Sending #{timespan} seconds to project #{projectuuid}"
        Ping::ping(projectuuid, timespan, Projects::pingRetainPeriodInSeconds())
        puts "Sending #{timespan} seconds to item #{itemuuid}"
        Ping::ping(itemuuid, timespan, Projects::pingRetainPeriodInSeconds())
    end

    Projects::recastItem(projectuuid, itemuuid)
end

if ARGV[0] == "open" and ARGV[1] and ARGV[2] then
    projectuuid = ARGV[1]
    exit if !projectuuidIsValid(projectuuid)

    itemuuid = ARGV[2]
    exit if !itemuuidIsValid(projectuuid, itemuuid)

    item = Projects::getItemOrNull(projectuuid, itemuuid)
    exit if item.nil
    puts JSON.pretty_generate(item)
    Projects::openItem(item)
end

if ARGV[0] == "start" and ARGV[1] and ARGV[2] then
    projectuuid = ARGV[1]
    exit if !projectuuidIsValid(projectuuid)

    itemuuid = ARGV[2]
    exit if !itemuuidIsValid(projectuuid, itemuuid)

    Runner::start(itemuuid)

    if projectuuid == "44caf74675ceb79ba5cc13bafa102509369c2b53" then
        item = Projects::getItemOrNull(projectuuid, itemuuid)
        CatalystStandardTarget::openTarget(item["target"])
    else
        if LucilleCore::askQuestionAnswerAsBoolean("-> open ? ", true) then
            item = Projects::getItemOrNull(projectuuid, itemuuid)
            CatalystStandardTarget::openTarget(item["target"])
        end
    end

    if LucilleCore::askQuestionAnswerAsBoolean("-> done ? ", false) then
        item = Projects::getItemOrNull(projectuuid, itemuuid)
        processing_done(projectuuid, itemuuid)
    else
        if projectuuid == "44caf74675ceb79ba5cc13bafa102509369c2b53" then
            puts "-> Going to recast"
            processing_recast(projectuuid, itemuuid)
        end
    end
end

if ARGV[0] == "stop" and ARGV[1] and ARGV[2] then
    projectuuid = ARGV[1]
    exit if !projectuuidIsValid(projectuuid)

    itemuuid = ARGV[2]
    exit if !itemuuidIsValid(projectuuid, itemuuid)

    timespan = Runner::stop(itemuuid)
    exit if timespan.nil?

    timespan = [timespan, 3600*2].min # To avoid problems after leaving things running
    puts "Sending #{timespan} seconds to project #{projectuuid}"
    Ping::ping(projectuuid, timespan, Projects::pingRetainPeriodInSeconds())
    puts "Sending #{timespan} seconds to item #{itemuuid}"
    Ping::ping(itemuuid, timespan, Projects::pingRetainPeriodInSeconds())
end

if ARGV[0] == "done" and ARGV[1] and ARGV[2] then
    projectuuid = ARGV[1]
    exit if !projectuuidIsValid(projectuuid)

    itemuuid = ARGV[2]
    exit if !itemuuidIsValid(projectuuid, itemuuid)

    processing_done(projectuuid, itemuuid)
end

if ARGV[0] == "description" and ARGV[1] and ARGV[2] then
    projectuuid = ARGV[1]
    exit if !projectuuidIsValid(projectuuid)

    itemuuid = ARGV[2]
    exit if !itemuuidIsValid(projectuuid, itemuuid)

    item = Projects::getItemOrNull(projectuuid, itemuuid)
    item["description"] = CatalystCommon::editTextUsingTextmate(item["description"])
    Projects::attachItemToProject(projectuuid, item)
end

if ARGV[0] == "make-ifcs-claim" and ARGV[1] and ARGV[2] then
    projectuuid = ARGV[1]
    exit if !projectuuidIsValid(projectuuid)

    itemuuid = ARGV[2]
    exit if !itemuuidIsValid(projectuuid, itemuuid)

    position = Projects::nextIfcsPosition()
    Projects::issueIfcsClaimTypeItem(projectuuid, itemuuid, position)
end

if ARGV[0] == "recast" and ARGV[1] and ARGV[2] then
    projectuuid = ARGV[1]
    exit if !projectuuidIsValid(projectuuid)

    itemuuid = ARGV[2]
    exit if !itemuuidIsValid(projectuuid, itemuuid)
    
    processing_recast(projectuuid, itemuuid)
    puts "item #{itemuuid} recast at #{projectuuid}"
end
