#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require_relative "Core/Core.rb"

# --------------------------------------------------------------------

Projects::projects()
    .each{|project|
        Items::getItemsByCreationTime(project["uuid"])
            .each{|item|
                uuid = item["uuid"]
                next if !Runner::isRunning(uuid)
                next if (Runner::runTimeInSecondsOrNull(uuid) || 0) < 3600
                CatalystCommon::onScreenNotification("Projects Time Control", "item '#{Items::itemBestDescription(item)}' is running for more than an hour")
                exit
            }
    }

