#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require_relative "Projects.rb"

# --------------------------------------------------------------------

Projects::getIFCSProjectsOrderedByPosition()
.each{|project|
    uuid = project["uuid"]
    next if !Runner::isRunning(uuid)
    # The item is running
    next if !Runner::runTimeInSecondsOrNull(uuid)
    next if Runner::runTimeInSecondsOrNull(uuid) < 3600
    CatalystCommon::onScreenNotification("In Flight Control System", "#{project["description"]} is running for more than an hour")
    exit
}
