#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require 'json'
# JSON.pretty_generate(object)

require 'fileutils'
# FileUtils.mkpath '/a/b/c'
# FileUtils.cp(src, dst)
# FileUtils.mv 'oldname', 'newname'
# FileUtils.rm(path_to_image)
# FileUtils.rm_rf('dir/to/remove')

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/LucilleCore.rb"

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/KeyValueStore.rb"
=begin
    KeyValueStore::setFlagTrue(repositorylocation or nil, key)
    KeyValueStore::setFlagFalse(repositorylocation or nil, key)
    KeyValueStore::flagIsTrue(repositorylocation or nil, key)

    KeyValueStore::set(repositorylocation or nil, key, value)
    KeyValueStore::getOrNull(repositorylocation or nil, key)
    KeyValueStore::getOrDefaultValue(repositorylocation or nil, key, defaultValue)
    KeyValueStore::destroy(repositorylocation or nil, key)
=end

# --------------------------------------------------------------------

require_relative "Core/Core.rb"

# -----------------------------------------------------------------------------

if ARGV[0] == "start" and ARGV[1] and ARGV[2] then
    uuid = ARGV[1]
    exit if uuid.nil?
    item = Items::getOrNull(uuid)
    exit if item.nil?

    Runner::start(uuid)
    CatalystStandardTarget::openTarget(item["target"])
end

if ARGV[0] == "open" and ARGV[1] and ARGV[2] then
    uuid = ARGV[1]
    exit if uuid.nil?
    item = Items::getOrNull(uuid)
    exit if item.nil?

    CatalystStandardTarget::openTarget(item["target"])
end

if ARGV[0] == "stop" and ARGV[1] then
    uuid = ARGV[1]
    exit if uuid.nil?
    item = Items::getOrNull(uuid)
    exit if item.nil?

    timespan = Runner::stop(uuid)
    exit if timespan.nil?

    timespan = [timespan, 3600*2].min # To avoid problems after leaving things running
    Items::receiveRunTimespan(item, timespan)
end

if ARGV[0] == "done" and ARGV[1] then
    uuid = ARGV[1]
    exit if uuid.nil?
    item = Items::getOrNull(uuid)
    exit if item.nil?

    timespan = Runner::stop(uuid)
    if timespan.nil? then
        timespan = [timespan, 3600*2].min # To avoid problems after leaving things running
        Items::receiveRunTimespan(item, timespan)
    end

    Items::destroy(item)
end

if ARGV[0] == "dive" and ARGV[1] then
    uuid = ARGV[1]
    exit if uuid.nil?
    item = Items::getOrNull(uuid)
    exit if item.nil?

    Items::diveItem(item)
end
