#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require_relative "InFlightControlSystem.rb"

# --------------------------------------------------------------------

IFCS::itemsOrderedByPosition()
.each{|item|
    next if !InFlightControlSystem::isRunning(item["targetuid"])
    # The item is running
    next if !InFlightControlSystem::runTimeInSecondsOrNull(item["targetuid"])
    next if InFlightControlSystem::runTimeInSecondsOrNull(item["targetuid"]) < 3600
    IFCS::onScreenNotification("In Flight Control System", "#{item["description"]} is running for more than an hour")
    sleep 1
    exit
}
