#!/usr/bin/ruby

# encoding: UTF-8

require_relative "loader.rb"

# -------------------------------------------------------------------------

CATALYST_RUN_HASH = SecureRandom.hex
CATALYST_CODE_FOLDERPATH = File.dirname(File.dirname(__FILE__)) 
STARTING_CODE_HASH = EstateServices::locationHashRecursively(CATALYST_CODE_FOLDERPATH)

# -------------------------------------------------------------------------
# nslog

# -------------------------------------------------------------------------

EstateServices::ensureReadiness()
CatalystUI::standardUILoop()

# -------------------------------------------------------------------------
