#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Libs/loader.rb"

# ----------------------------------------------------------------------------

puts UIServices::mainMenuCommands().yellow
command = LucilleCore::askQuestionAnswerAsString("> ")
UIServices::mainMenuInterpreter(command)

