#!/usr/bin/ruby

# encoding: UTF-8

require 'json'

require 'date'

require 'colorize'

require 'securerandom'
# SecureRandom.hex    #=> "eb693ec8252cd630102fd0d0fb7c3485"
# SecureRandom.hex(4) #=> "eb693123"
# SecureRandom.uuid   #=> "2d931510-d99f-494a-8c67-87feb05e1594"

require 'fileutils'
# FileUtils.mkpath '/a/b/c'
# FileUtils.cp(src, dst)
# FileUtils.mv 'oldname', 'newname'
# FileUtils.rm(path_to_image)
# FileUtils.rm_rf('dir/to/remove')
require 'digest/sha1'
# Digest::SHA1.hexdigest 'foo'
# Digest::SHA1.file(myFile).hexdigest
require 'find'

require 'digest/sha1'
# Digest::SHA1.hexdigest 'foo'
# Digest::SHA1.file(myFile).hexdigest

require 'drb/drb'

require "/Galaxy/local-resources/Ruby-Libraries/LucilleCore.rb"
require "/Galaxy/LucilleOS/Librarian/Librarian-Exported-Functions.rb"

require_relative "Wave-Emails.rb"
require_relative "Constants.rb"
require_relative "Events.rb"
require_relative "Events.rb"
require_relative "MiniFIFOQ.rb"
require_relative "Config.rb"
require_relative "GenericTimeTracking.rb"
require_relative "CatalystDevOps.rb"
require_relative "CollectionsCore.rb"
require_relative "NotGuardian"
require_relative "FolderProbe.rb"
require_relative "CommonsUtils"

require_relative "Agent-Collections.rb"
require_relative "Agent-DailyTimeAttribution.rb"
require_relative "Agent-Ninja.rb"
require_relative "Agent-Stream.rb"
require_relative "Agent-TimeCommitments.rb"
require_relative "Agent-Today.rb"
require_relative "Agent-Vienna.rb"
require_relative "Agent-Wave.rb"

require_relative "TheFlock.rb"

# -----------------------------------------------------------------

class CatalystCLIUtils
    def self.cli(runId)
        mainschedule = {}
        mainschedule["archives-gc"] = Time.new.to_i + Random::rand*86400
        mainschedule["events-gc"]   = Time.new.to_i + Random::rand*86400
        mainschedule["requirements-off-notification"] = Time.new.to_i + Random::rand*3600*2
        loop {
            FlockDiskIO::loadFromEventsTimeline()
            object = FlockService::topObjects(1).first
            # --------------------------------------------------------------------------------
            # Sometimes a wave item that is an email, gets deleted by the Wave-Emails process.
            # In such a case they are still in Flock and should not be showed
            if object["agent-uid"]=="283d34dd-c871-4a55-8610-31e7c762fb0d" then
                if object["schedule"][":wave-emails:"] then
                    if !File.exists?(object["item-data"]["folderpath"]) then
                        puts CommonsUtils::object2Line_v0(object)
                        puts "This email has been deleted, removing Flock item:"
                        FlockOperator::removeObjectIdentifiedByUUID(object["uuid"])
                        EventsManager::commitEventToTimeline(EventsMaker::destroyCatalystObject(object["uuid"]))
                        next
                    end
                end
            end
            system("clear")
            if ( Time.new.to_i > mainschedule["archives-gc"] ) and CommonsUtils::isLucille18() then
                lines = CatalystDevOps::archivesTimelineGarbageCollection()
                puts "Archives timeline garbage collection: #{lines.size}"
                lines.each{|line|
                    puts "    - #{line}"
                }
                LucilleCore::pressEnterToContinue() if lines.size>0
                mainschedule["archives-gc"] = Time.new.to_i + Random::rand*86400
            end
            if ( Time.new.to_i > mainschedule["events-gc"] ) and CommonsUtils::isLucille18() then
                lines = CatalystDevOps::eventsTimelineGarbageCollection()
                puts "Events timeline garbage collection: #{lines.size}"
                lines.each{|line|
                    puts "    - #{line}"
                }
                LucilleCore::pressEnterToContinue() if lines.size>0
                mainschedule["events-gc"] = Time.new.to_i + Random::rand*86400
            end
            if ( Time.new.to_i > mainschedule["requirements-off-notification"] ) then
                if RequirementsOperator::getCurrentlyUnsatisfiedRequirements().size>0 then
                    puts "REQUIREMENTS OFF: #{RequirementsOperator::getCurrentlyUnsatisfiedRequirements().join(", ")}"
                    LucilleCore::pressEnterToContinue()
                end
                mainschedule["requirements-off-notification"] = Time.new.to_i + Random::rand*3600*2
                next
            end
            puts CatalystCLIUtils::object2Line_v1(object)
            print "--> "
            command = STDIN.gets().strip
            if command.start_with?(":") then
                x = command[1,command.size].strip
                if CommonsUtils::isInteger(x) then
                    CommonsUtils::doPresentObjectInviteAndExecuteCommand(FlockService::topObjects(x.to_i).last)
                    next
                end
            end
            command = command.size>0 ? command : ( object["default-expression"] ? object["default-expression"] : "" )
            CommonsUtils::processObjectAndCommand(object, command)
            File.open("#{CATALYST_COMMON_DATABANK_FOLDERPATH}/run-identifier.data", "w") {|f| f.write(runId) }
        }
    end
    def self.object2Line_v1(object)
        announce = object['announce'].strip
        announce = CommonsUtils::announceWithColor(announce, object)
        defaultExpressionAsString = object["default-expression"] ? object["default-expression"] : ""
        requirements = RequirementsOperator::getObjectRequirements(object['uuid'])
        requirementsAsString = requirements.size>0 ? " ( #{requirements.join(" ")} )" : ''
        [
            "(#{"%.3f" % object["metric"]})",
            " [#{object["uuid"]}]",
            " #{announce}",
            "#{requirementsAsString.green}",
            CommonsUtils::object2DonotShowUntilAsString(object),
            " (#{object["commands"].join(" ").red})",
            " \"#{defaultExpressionAsString.green}\""
        ].join()
    end
end

runId = SecureRandom.hex

FlockDiskIO::loadFromEventsTimeline()

Thread.new {
    loop {
        if CommonsUtils::isActiveInstance(runId) then
            CommonsUtils::emailSync(false)
        end
        sleep 1200
    }
}

CatalystCLIUtils::cli(runId)
