#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Implementations/Ruby/loader.rb"

# ----------------------------------------------------------------------------

loop {
    system("clear")

    puts ""

    content = IO.read("/Users/pascal/Desktop/Today.txt")
                .split('@separation-efd2f62e-5ffe-4658-a3e6-c38bdea08136')
                .first
    puts content.lines.first(CatalystUtils::screenHeight()-4).join()

    ns16 = UIServices::todayNS16s().first

    ns16["lambda"].call()
}



