#!/usr/bin/ruby

# encoding: UTF-8

require_relative "TheOperator.rb"

# -------------------------------------------------------------------------------------

flock = {}
TheOperator::flockGeneralUpgrade(flock).each{|object|
    puts "#{object['announce'].lines.first}"
}
