#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Libs/loader.rb"

# ----------------------------------------------------------------------------

Thread.new {
    loop {
        sleep 3600
        system("#{File.dirname(__FILE__)}/vienna-import")
    }
}

Thread.new {
    loop {
        # We wait for 2 mins and then we add to the current universe
        sleep 120
        universe = StoredUniverse::getUniverse()
        UniverseAccounting::addTimeToUniverse(universe, 120)
    }
}

TerminalDisplayOperator::standardDisplayLoop()
