#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Libs/loader.rb"

# ----------------------------------------------------------------------------


if ARGV.empty? then
    puts "usage:"
    puts "catalyst no-work-today"
    exit
end

if ARGV[0] == "no-work-today" then
    KeyValueStore::setFlagTrue(nil, "a2f220ce-e020-46d9-ba64-3938ca3b69d4:#{Utils::today()}")
    exit
end
