#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Wave.rb"
require_relative "CatalystCore.rb"

# -------------------------------------------------------------------------------------

WaveTimelineUtils::getCatalystObjects().each{|object|
    puts "#{object['announce'].lines.first}"
}

