#!/usr/bin/ruby

# encoding: UTF-8

require_relative "loader.rb"

# -------------------------------------------------------------------------

CATALYST_RUN_HASH = SecureRandom.hex
CATALYST_CODE_FOLDERPATH = File.dirname(File.dirname(__FILE__)) 
STARTING_CODE_HASH = EstateServices::locationHashRecursively(CATALYST_CODE_FOLDERPATH)

# -------------------------------------------------------------------------
# nslog

# -------------------------------------------------------------------------

EstateServices::surveyAndConstruction()
NetworkManager::ensureBasicNetworkPrinciples()

CatalystObjectsOperator::getCatalystListingObjectsOrdered() 
    # We run this to build the necessary cachings before the thread start.
    # Otherwise we might end up with the main thread and the secondary thread doing the same thing

Thread.new {
    loop {
        sleep 10
        CatalystObjectsOperator::getCatalystListingObjectsOrdered()
            .select{|object| object["isRunningForLong"] }
            .first(1)
            .each{|object|
                Miscellaneous::onScreenNotification("Catalyst Interface", "An object is running for long")
            }
        sleep 60
    }
}

CatalystUI::standardUILoop()

# -------------------------------------------------------------------------
