#!/usr/bin/ruby

# encoding: UTF-8

require_relative "CatalystObjects.rb"

# -------------------------------------------------------------------------------------

CatalystCore::objects().each{|object|
    puts "#{object['announce'].lines.first}"
}

