#!/usr/bin/ruby

# encoding: UTF-8

$RunNonEssentialThreads = false

require_relative "Libs/loader.rb"

# --------------------------------------------------------------------

loop {
    sleep 10
    SystemEvents::processIncomingEventsFromLine(true)
}
