#!/usr/bin/ruby

# encoding: UTF-8

$RunNonEssentialThreads = false

require_relative "Libs/loader.rb"

# --------------------------------------------------------------------

loop {
    sleep 1
    SystemEvents::processIncomingEventsFromLine(true)
    CommsLine::moveCarefully(true)
}
