#!/usr/bin/ruby

# encoding: UTF-8

$RunNonEssentialThreads = false

require_relative "Libs/loader.rb"

# ----------------------------------------------------------------------------

location1 = ARGV[0]
location2 = ARGV[1]

puts CommonUtils::firstDifferenceBetweenTwoLocations(location1, location2)

