
# encoding: UTF-8

CATALYST_COMMON_DATABANK_FOLDERPATH = "/Galaxy/DataBank/Catalyst"
CATALYST_COMMON_CONFIG_FILEPATH = "#{CATALYST_COMMON_DATABANK_FOLDERPATH}/Config.json"
CATALYST_COMMON_BIN_ARCHIVES_TIMELINE_FOLDERPATH = "#{CATALYST_COMMON_DATABANK_FOLDERPATH}/Bin-Timeline"
CATALYST_COMMON_PATH_TO_STREAM_DATA_FOLDER = "#{CATALYST_COMMON_DATABANK_FOLDERPATH}/Agents-Data/Stream"
CATALYST_COMMON_PATH_TO_EVENTS_TIMELINE = "/Galaxy/DataBank/Catalyst/Events-Timeline"
CATALYST_COMMON_AGENTSTREAM_METRIC_GENERIC_TIME_TRACKING_KEY = "2EECA0DE-F4BD-471C-A26A-3F2670C07A69"
CATALYST_COMMON_TIMEPOINTS_ITEMS_SETUUID = "64cba051-9761-4445-8cd5-8cf49c105ba1" unless defined? CATALYST_COMMON_TIMEPOINTS_ITEMS_SETUUID
CATALYST_COMMON_TIMEPOINTS_ITEMS_REPOSITORY_PATH = "#{CATALYST_COMMON_DATABANK_FOLDERPATH}/Agents-Data/time-points/timepoints" unless defined? CATALYST_COMMON_TIMEPOINTS_ITEMS_REPOSITORY_PATH
