#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Libs/loader.rb"

NxPods::getNxPods().each{|nxpod|
    puts nxpod["uuid"]
    NxPdFileSystemAdapter::fsckNxPod(nxpod["uuid"])
}
puts "All good!".green
