#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Libs/loader.rb"

NxPods::getNxPods().each{|nxpod|
    puts nxpod.id()
    NxPods::fsckNxPod(nxpod.id())
}
NxNavs::getNxNavs().each{|nxnav|
    puts nxnav.id()
    NxNavs::fsckNxNav(nxnav.id())
}
puts "All good!".green
