#!/usr/bin/ruby

# encoding: UTF-8

$RunNonEssentialThreads = false

require_relative "Libs/loader.rb"

# ----------------------------------------------------------------------------

filepaths = LucilleCore::locationsAtFolder(Dir.pwd)
                .select{|filepath| filepath[-4, 4] == ".Nx7" }

filepath = LucilleCore::selectEntityFromListOfEntitiesOrNull("Nx7", filepaths, lambda{|filepath| File.basename(filepath) })

exportFolder = filepath.gsub(".Nx7", "")
if File.exists?(exportFolder) then
    puts "There already is an export folder for: #{File.basename(filepath)}"
    exit
end
item = Nx5Ext::readFileAsAttributesOfObject(filepath)
operator = ElizabethNx5.new(filepath)
state = item["nx7Payload"]["state"]
FileUtils.mkdir(exportFolder)
GridState::exportStateAtFolder(operator, state, exportFolder)