#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Libs/loader.rb"

# ----------------------------------------------------------------------------

Sx01Snapshots::printSnapshotDeploymentStatusIfRelevant()

LibrarianCLI::main()
