#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Libs/loader.rb"

# ----------------------------------------------------------------------------

puts "commands: run fsck | show object | prob blob | do NS1 pickups | exit"

loop {
    command = LucilleCore::askQuestionAnswerAsString("(librarian) ")
    if command == "run fsck" then
        Librarian15Fsck::fsck()
        puts "fsck completed"
        LucilleCore::pressEnterToContinue()
    end
    if command == "show object" then
        uuid = LucilleCore::askQuestionAnswerAsString("uuid: ")
        object = Librarian6Objects::getObjectByUUIDOrNull(uuid)
        if object then
            puts JSON.pretty_generate(object)
            LucilleCore::pressEnterToContinue()
        else
            puts "I could not find an object with this uuid"
            LucilleCore::pressEnterToContinue()
        end
    end
    if command == "prob blob" then
        nhash = LucilleCore::askQuestionAnswerAsString("nhash: ")
        blob = Librarian12EnergyGrid::getBlobOrNull(nhash)
        if blob then
            if blob[0, 1] == "{" then
                puts "blob: #{blob}"
                puts JSON.pretty_generate(blob)
                LucilleCore::pressEnterToContinue()
            else
                puts "Found a blob of size #{blob.size}"
                LucilleCore::pressEnterToContinue()
            end
        else
            puts "I could not find a blob with nhash: #{nhash}"
            LucilleCore::pressEnterToContinue()
        end
    end
    if command == "do NS1 pickups" then
        Librarian16AionDispatch::doPickups()
    end
    if command == "exit" then
        break
    end
}