#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Libs/loader.rb"

# ----------------------------------------------------------------------------

puts Interpreters::makersAndDiversCommands().yellow
command = LucilleCore::askQuestionAnswerAsString("> ")
Interpreters::makersAndDiversInterpreter(command)

