#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Libs/loader.rb"

# ----------------------------------------------------------------------------

puts UIServices::makersAndDiversCommands().yellow
command = LucilleCore::askQuestionAnswerAsString("> ")
CentralDispatch::operator4(command)

