#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Libs/loader.rb"

# ----------------------------------------------------------------------------

uuid = SecureRandom.uuid

nx50 = {}
nx50["uuid"]        = uuid
nx50["schema"]      = "Nx50"
nx50["unixtime"]    = Time.new.to_f

description = LucilleCore::askQuestionAnswerAsString("description (empty for abort): ")
if description == "" then
    exit
end

nx50["contentType"] = description

coordinates = Nx102::interactivelyIssueNewCoordinates3OrNull()
exit if coordinates.nil?

nx50["contentType"] = coordinates[0]
nx50["payload"]     = coordinates[1]

CoreDataTx::commit(nx50)