
# encoding: UTF-8

CATALYST_COMMON_DATABANK_CATALYST_FOLDERPATH = "/Galaxy/DataBank/Catalyst"
CATALYST_COMMON_BIN_ARCHIVES_TIMELINE_FOLDERPATH = "#{CATALYST_COMMON_DATABANK_CATALYST_FOLDERPATH}/Bin-Timeline"
CATALYST_COMMON_PATH_TO_KV_REPOSITORY = "/Galaxy/DataBank/Catalyst/KeyValueStoreRepository"