
# encoding: UTF-8

CATALYST_COMMON_DATABANK_CATALYST_FOLDERPATH = "/Galaxy/DataBank/Catalyst"
CATALYST_COMMON_BIN_ARCHIVES_TIMELINE_FOLDERPATH = "#{CATALYST_COMMON_DATABANK_CATALYST_FOLDERPATH}/Bin-Timeline"

CATALYST_IPHETRA_DATA_REPOSITORY_FOLDERPATH = "/Galaxy/DataBank/Catalyst/Iphetra-Repository"
