#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Libs/loader.rb"

# ----------------------------------------------------------------------------

if ARGV[0] == "search" then
    Network::generalSearchLoop()
    exit
end

if ARGV[0] == "listing" then
    loop {
        id = LucilleCore::selectEntityFromListOfEntitiesOrNull("Asteroid", Network::ids(), lambda{|id| Network::description(id) })
        break if id.nil?
        Network::landing(id)
    }
    exit
end

if ARGV[0] == "make" then
    id = Network::interactivelyMakeNewNodeOrNull()
    exit if id.nil?
    Network::landing(id)
    exit
end

if ARGV[0] == "unique-string" then
    puts SecureRandom.hex(6)
    exit
end

if ARGV[0] == "fsck" then
    Network::ids().each{|id|
        puts "fsck: #{id}"
        Network::fsck(id)
    }
    puts "All good!".green
    exit
end

str = <<HELP
usage:
    nyx search
    nyx listing
    nyx make
    nyx unique-string # Generates a unique string for type FSUniqueString
    nyx fsck
    nyx help # help display
HELP
puts str

