#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Libs/loader.rb"

# ----------------------------------------------------------------------------

if ARGV[0] == "search" then
    Space::generalSearchLoop()
    exit
end

if ARGV[0] == "listing" then
    loop {
        nxpoint = LucilleCore::selectEntityFromListOfEntitiesOrNull("NxPoint", Space::getNxPoints(), lambda{|e| e.toString() })
        break if nxpoint.nil?
        Space::landing(nxpoint)
    }
    exit
end

if ARGV[0] == "make-new-NxPod" then
    nxpod = NxPods::interactivelyIssueNewNxPodOrNull()
    exit if nxpod.nil?
    Space::landing(nxpod)
    exit
end

if ARGV[0] == "stack" and ARGV[1] then
    id = ARGV[1]
    if !Space::idIsUsed(id) then
        puts "error: the provided id '#{id}' is not used"
        exit
    end
    puts "stacking '#{Space::idToNxPointOrNull(id).description()}'"
    IdStack::stack(id)
    exit
end

if ARGV[0] == "unstack" then
    IdStack::unStackOrNull()
    exit
end

str = <<HELP
usage:
    nyx search
    nyx listing
    nyx stack <NxId>
    nyx unstack 
    nyx help # help display
HELP
puts str

