#!/usr/bin/ruby

# encoding: UTF-8

require_relative "src/loader.rb"

# --------------------------------------------------------------------

namedhash = ARGV[0]
exit if namedhash.nil?
puts NyxBlobs::getBlobOrNull(namedhash)
