#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Implementations/Ruby/loader.rb"

# -------------------------------------------------------------------------

uniquestring = ARGV[0]

Quarks::quarks()
    .select{|quark|
        quark["type"] == "filesystem-unique-string"
    }
    .select{|quark|
        quark["mark"] == uniquestring
    }
    .each{|quark|
        puts Quarks::toString(quark)
    }