#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Libs/loader.rb"

# ----------------------------------------------------------------------------

description = LucilleCore::askQuestionAnswerAsString("description (empty to abort): ")
exit if description == ""
uuid  = SecureRandom.uuid
node = NightSky::spawn(uuid, description, "desktop")
coredataref = CoreData::interactivelyMakeNewReferenceStringOrNull(node)
if coredataref then
    node.coredataref_set(coredataref)
end
NightSky::landing(node)