#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Libs/loader.rb"

# ----------------------------------------------------------------------------

Thread.new {
    sleep 30
    Cubes::maintenance()
}

Nyx::main()
