#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Implementations/Ruby/loader.rb"

# ----------------------------------------------------------------------------

uuid = ARGV[0]
exit if uuid.nil?
item = NyxPatricia::getDX7ByUUIDOrNull(uuid) 
exit if item.nil?
NyxPatricia::dx7landing(item)
