#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Libs/loader.rb"

# ----------------------------------------------------------------------------

starttime = Time.new.to_f
NX141FSCacheElement::scan()
NX141FSCacheElement::garbageCollection(starttime)
