#!/usr/bin/ruby

# encoding: utf-8

require 'fileutils'
# FileUtils.mkpath '/a/b/c'
# FileUtils.cp(src, dst)
# FileUtils.mv('oldname', 'newname')
# FileUtils.rm(path_to_image)
# FileUtils.rm_rf('dir/to/remove')

require "/Galaxy/LucilleOS/Misc-Resources/Ruby-Libraries/LucilleCore.rb"

require 'securerandom'
# SecureRandom.hex    #=> "eb693ec8252cd630102fd0d0fb7c3485"
# SecureRandom.hex(4) #=> "1ac4eb69"
# SecureRandom.uuid   #=> "2d931510-d99f-494a-8c67-87feb05e1594"

require_relative "Projects.rb"

# ------------------------------------------------------------------------

projectName = LucilleCore::interactivelySelectEntityFromListOfEntitiesOrNull("Project: ",ProjectsCore::getProjectsNames())
projectuuid = ProjectsCore::projectNameToUuid(projectName)
DRbObject.new(nil, "druby://:10423").stopAndAddTimeSpan(projectuuid)

