#!/usr/bin/ruby

# encoding: UTF-8

$RunNonEssentialThreads = true

require_relative "Libs/loader.rb"

# ----------------------------------------------------------------------------

CatalystListing::streaming()
