#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Wave.rb"

# ----------------------------------------------------------------------------

puts WaveDevOps::getArchiveSizeInMegaBytes()
WaveDevOps::archivesGarbageCollection(true)

