#!/usr/bin/ruby

require_relative "Wave.rb"

if ARGV[0].nil? then
    puts "You need to provide the description of the item."
    exit
end

description = ARGV[0].strip
exit if description.size==0
uuid = SecureRandom.hex(4)

if ARGV[1].nil? then
    schedule = WaveSchedules::makeScheduleObjectInteractivelyOrNull()
else
    datecode = ARGV[1]
    schedule = WaveSchedules::makeScheduleObjectNew()
    datetime = LucilleCore::datetimeSpecification2232ToDatetime(datecode)
    schedule["do-not-show-until-datetime"] = datetime
end

puts JSON.pretty_generate(schedule)
folderpath = WaveTimelineUtils::timestring22ToFolderpath(LucilleCore::timeStringL22())
FileUtils.mkpath folderpath
File.open("#{folderpath}/catalyst-uuid", 'w') {|f| f.write(uuid) }
File.open("#{folderpath}/catalyst-description.txt", 'w') {|f| f.write(description) }
WaveTimelineUtils::writeScheduleToDisk(uuid, schedule)
