#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Wave-Emails.rb"

# ----------------------------------------------------------------------------

GeneralEmailClient::syncEmailDataWithServer(JSON.parse(IO.read("#{CATALYST_COMMON_AGENT_DATA_FOLDERPATH}/Wave/Wave-Email-Config/guardian-relay.json")), true)
OperatorEmailDownloader::syncEmailDataWithServer(JSON.parse(IO.read("#{CATALYST_COMMON_AGENT_DATA_FOLDERPATH}/Wave/Wave-Email-Config/operator.json")), true)

