#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Agent-Wave.rb"

# ----------------------------------------------------------------------------

puts CatalystDevOps::getArchiveSizeInMegaBytes()
CatalystDevOps::archivesGarbageCollection(true)

