#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Wave.rb"

# ----------------------------------------------------------------------------

puts CatalystArchivesOps::getArchiveSizeInMegaBytes()
CatalystArchivesOps::archivesGarbageCollection(true)

