#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Wave-Emails.rb"

# ----------------------------------------------------------------------------

GeneralEmailClient::downloadDataFromServer(JSON.parse(IO.read("/Galaxy/DataBank/Catalyst/Wave-Email-Config/guardian-relay.json")), true)
OperatorEmailDownloader::downloadDataFromServer(JSON.parse(IO.read("/Galaxy/DataBank/Catalyst/Wave-Email-Config/operator.json")), true)

