#!/usr/bin/ruby

# encoding: UTF-8

require_relative "src/loader.rb"

# -------------------------------------------------------------------------

DataPortalUI::dataPortalFront()

# -------------------------------------------------------------------------
