#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Libs/loader.rb"

# ----------------------------------------------------------------------------

puts Interpreters::mainMenuCommands().yellow
command = LucilleCore::askQuestionAnswerAsString("> ")
Interpreters::mainMenuInterpreter(command)

