#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Libs/loader.rb"

# ----------------------------------------------------------------------------

entity = NxEntitiesinteractivelyCreateNewEntityOrNull()
exit if entity.nil?
NxEntitieslanding(entity)
