#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Libs/loader.rb"

# ----------------------------------------------------------------------------

entity = NyxEntities::interactivelyCreateNewEntityOrNull()
exit if entity.nil?
NyxEntities::landing(entity)
