#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Libs/loader.rb"

# ----------------------------------------------------------------------------

entity = NxEntity::interactivelyCreateNewEntityOrNull()
exit if entity.nil?
NxEntity::landing(entity)
