
# encoding: UTF-8

CATALYST_COMMON_DATABANK_CATALYST_SHARED_FOLDERPATH = "/Users/pascal/Galaxy/DataBank/Catalyst-Shared-Streams"
CATALYST_COMMON_DATABANK_CATALYST_INSTANCE_FOLDERPATH = "/Users/pascal/Galaxy/DataBank/Catalyst-#{ENV["COMPUTERLUCILLENAME"]}"
CATALYST_COMMON_BIN_ARCHIVES_TIMELINE_FOLDERPATH = "#{CATALYST_COMMON_DATABANK_CATALYST_SHARED_FOLDERPATH}/Bin-Timeline"
