
# encoding: UTF-8

DATABANK_CATALYST_FOLDERPATH = "/Users/pascal/Galaxy/DataBank/Catalyst"
CATALYST_BIN_TIMELINE_FOLDERPATH = "#{DATABANK_CATALYST_FOLDERPATH}/Bin-Timeline"
CATALYST_INSTANCE_FOLDERPATH = "#{DATABANK_CATALYST_FOLDERPATH}/Instances/#{ENV["COMPUTERLUCILLENAME"]}"

CATALYST_INBOX_STREAMUUID = "03b79978bcf7a712953c5543a9df9047"

