#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

puts "Temporarily disabled until we learnt to send only the missing data and only to targetted instances"
exit

SystemEvents::broadcast({
    "mikuType" => "ItemToGroupMapping-records",
    "records"  => ItemToGroupMapping::records()
})

SystemEvents::broadcast({
    "mikuType" => "Bank-records",
    "records"  => Bank::records()
})

SystemEvents::broadcast({
    "mikuType" => "Fx18-records",
    "records"  => Fx256::rows()
})

SystemEvents::broadcast({
    "mikuType" => "NetworkLinks-records",
    "records"  => NetworkLinks::records()
})
