#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

filepath1 = OwnerMapping::databaseFile()
Machines::theOtherInstanceIds().each{|targetInstanceId|
    filepath2 = "#{Config::starlightCommsLine()}/#{targetInstanceId}/#{CommonUtils::timeStringL22()}.owner-mapping.sqlite3"
    FileUtils.cp(filepath1, filepath2)
}

filepath1 = Bank::pathToBank()
Machines::theOtherInstanceIds().each{|targetInstanceId|
    filepath2 = "#{Config::starlightCommsLine()}/#{targetInstanceId}/#{CommonUtils::timeStringL22()}.bank.sqlite3"
    FileUtils.cp(filepath1, filepath2)
}

filepath1 = NetworkLinks::databaseFile()
Machines::theOtherInstanceIds().each{|targetInstanceId|
    filepath2 = "#{Config::starlightCommsLine()}/#{targetInstanceId}/#{CommonUtils::timeStringL22()}.network-links.sqlite3"
    FileUtils.cp(filepath1, filepath2)
}

exit

SystemEvents::broadcast({
    "mikuType" => "DxF1-records",
    "records"  => DxF1Extended::records()
})
