#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

SystemEvents::broadcast({
    "mikuType" => "OwnerMapping-records",
    "records"  => OwnerMapping::records()
})

SystemEvents::broadcast({
    "mikuType" => "Bank-records",
    "records"  => Bank::records()
})

SystemEvents::broadcast({
    "mikuType" => "NetworkLinks-records",
    "records"  => NetworkLinks::records()
})

SystemEvents::broadcast({
    "mikuType" => "DxF1-records",
    "records"  => DxF1Extended::records()
})
