#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

dbFilepath = OwnerMapping::databaseFile()

Machines::theOtherInstanceIds().each{|targetInstanceId|
    targetFilepath = "#{Config::starlightCommsLine()}/#{targetInstanceId}/#{CommonUtils::timeStringL22()}.owner-mapping.sqlite3"
    FileUtils.cp(dbFilepath, targetFilepath)
}

exit

SystemEvents::broadcast({
    "mikuType" => "Bank-records",
    "records"  => Bank::records()
})

SystemEvents::broadcast({
    "mikuType" => "NetworkLinks-records",
    "records"  => NetworkLinks::records()
})

SystemEvents::broadcast({
    "mikuType" => "DxF1-records",
    "records"  => DxF1Extended::records()
})
