#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

uuid = LucilleCore::askQuestionAnswerAsString("uuid: ")

SystemEvents::processAndBroadcast({
    "mikuType"   => "NxFileDeletion",
    "objectuuid" => uuid
})
