#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

uuid = LucilleCore::askQuestionAnswerAsString("uuid: ")
item = Catalyst::getCatalystItemOrNull(uuid)
if item.nil? then
    puts "Could not determine an item for this uuid"
    exit
end
puts JSON.pretty_generate(item)
LucilleCore::pressEnterToContinue()

NxTriages::destroy(uuid)
NxOndates::destroy(uuid)
ItemsManager::destroy("Wave", uuid)
NxTodos::destroy(uuid)
