#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

objectuuid = ARGV[0]

puts "From the index:"
puts JSON.pretty_generate(Items::getItemOrNull(objectuuid))

puts "From the Dxf1 file:"
puts JSON.pretty_generate(ItemsEventsLog::getProtoItemOrNull(objectuuid))
