#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

objectuuid = ARGV[0]
item = Items::getItemOrNull(objectuuid)
if item.nil? then
    puts "Could not find item for this uuid"
    exit
end
puts JSON.pretty_generate(item)

