#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

exit if ARGV[0].nil?

variant = ARGV[0]
object = Librarian::getObjectByVariantOrNull(variant)
if object then
    object = CommonUtils::editTextSynchronously(JSON.pretty_generate(object))
    object = JSON.parse(object)

    db = SQLite3::Database.new(Librarian::pathToObjectsDatabaseFile())
    db.execute "delete from _objects_ where _variant_=?", [variant]
    db.execute "insert into _objects_ (_uuid_, _variant_, _mikuType_, _object_) values (?, ?, ?, ?)", [object["uuid"], object["variant"], object["mikuType"], JSON.generate(object)]
    db.close

else
    puts "I could not find an object with this variant"
    LucilleCore::pressEnterToContinue()
end
