#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

exit if ARGV[0].nil?

uuid = ARGV[0]
object = Librarian::getObjectByUUIDOrNull(uuid)
if object then
    object = CommonUtils::editTextSynchronously(JSON.pretty_generate(object))
    object = JSON.parse(object)
    Librarian::commit(object)
else
    puts "I could not find an object with this uuid"
    LucilleCore::pressEnterToContinue()
end
