#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

exit if ARGV[0].nil?

variant = ARGV[0]
object = Librarian::getObjectByVariantOrNull(variant)
if object.nil? then
    puts "I could not find an object with this variant"
    exit
end
FileSystemCheck::fsckLibrarianMikuObjectExitAtFirstFailure(object, true)
puts "fsck completed successfully".green
