#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

objectuuid = ARGV[0]
item = Items::getItemOrNull(objectuuid)
if item.nil? then
    puts "no item with this uuid"
    exit
end
FileSystemCheck::fsck_MikuTypedItem(item, SecureRandom.hex, true)
puts "fsck completed successfully".green
