#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

runhash = 
    if LucilleCore::askQuestionAnswerAsBoolean("Use current runhash ? (the alternative is to issue a new one) ", true) then
        FileSystemCheck::getExistingRunHash()
    else
        r = SecureRandom.hex
        XCache::set("371dbc1d-8fbc-498b-ac98-d17d978cfdbf", r)
        r
    end

FileSystemCheck::fsckErrorAtFirstFailure(runhash)
