#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

exit if ARGV[0].nil?

uuid = ARGV[0]
object = Librarian::getObjectByUUIDOrNullEnforceUnique(uuid)
if object.nil? then
    puts "I could not find an object with this uuid"
    exit
end
operator = EnergyGridElizabeth.new()
FileSystemCheck::fsckLibrarianMikuObjectExitAtFirstFailure(object, operator)
puts "fsck completed successfully".green
