#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

exit if ARGV[0].nil?

mikuType = ARGV[0]

Librarian::getObjectsByMikuType(mikuType).each{|item|
    operator = EnergyGridClassicElizabeth.new()
    FileSystemCheck::fsckLibrarianMikuObjectExitAtFirstFailure(item, operator, true)
}
puts "fsck completed successfully".green

