#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

shouldReset = (ARGV[0] == "reset")
repository = "#{StargateCentral::pathToCentral()}/Fx18s"
Fx18Utils::fsckRepository(repository, shouldReset)
