#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

Librarian::objects()
    .each {|object|
        exit if !File.exists?("/Users/pascal/Desktop/Pascal.png")
        next if XCache::getFlag("625ef9cb-9586-4537-97e9-f25daed3bca5:#{JSON.generate(object)}")
        operator = EnergyGridElizabeth.new()
        FileSystemCheck::fsckLibrarianMikuObjectExitAtFirstFailure(object, operator)
        XCache::setFlag("625ef9cb-9586-4537-97e9-f25daed3bca5:#{JSON.generate(object)}", true)
    }

puts "fsck completed successfully".green
