#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

objectuuid = ARGV[0]
FileSystemCheck::fsckObjectuuidErrorAtFirstFailure(objectuuid, SecureRandom.hex, true)
puts "fsck completed successfully".green
