#!/usr/bin/ruby

require 'drb/drb'
require 'thread'

require_relative "../Libs/loader.rb"

puts "Starting server"

class ScoreService

  def eventForServer(event)
    puts "incoming event:"
    puts JSON.pretty_generate(event)
    #SyncEventsBase::processEvent(event)
  end

  def getEventForClientOrNull()
    event = Mercury::dequeueFirstValueOrNull("75D88016-56AA-4729-992A-F1FF62AAF893:Lucille18")
    return if event.nil?
    puts "outgoing event:"
    puts JSON.pretty_generate(event)
    event
  end

  def getBlobOrNull(nhash)
    EnergyGridDatablobs::getBlobOrNull(nhash)
  end

end

DRb.start_service("druby://192.168.0.3:9876", ScoreService.new())
DRb.thread.join
