#!/usr/bin/ruby

require_relative "../Libs/loader.rb"

require 'drb/drb'

loop {
    event = DRbObject.new(nil, "druby://192.168.0.3:9876").getEventForClientOrNull()
    break if event.nil?
    SyncEventsBase::processEvent(event)
}
