#!/usr/bin/ruby

require_relative "../Libs/loader.rb"

require 'drb/drb'

loop {
    event = DRbObject.new(nil, "druby://192.168.0.3:9876").getEventForClientOrNull()
    break if event.nil?
    puts "incoming event:"
    puts JSON.pretty_generate(event)
    SyncEventsBase::processEvent(event)
}

loop {
    event = Mercury::dequeueFirstValueOrNull("75D88016-56AA-4729-992A-F1FF62AAF893:Lucille20")
    break if event.nil?
    puts "outgoing event:"
    puts JSON.pretty_generate(event)
    DRbObject.new(nil, "druby://192.168.0.3:9876").eventForServer(event)
}
