#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

itemuuid = Architect::interactivelyMakeNewOrNull()
exit if itemuuid.nil?
item = Fx18::itemOrNull(itemuuid)
LxAction::action("landing", item)
