#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

item = Nyx::interactivelyMakeNewOrNull()
exit if item.nil?
item = Fx18s::getAliveItemOrNull(item["uuid"])
if item.nil? then
    raise "(error: d628570c-db78-45d0-83de-0535cf44533b) this should not have hapenned 🤔"
end
LxAction::action("landing", item)
