#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

puts CommandInterpreters::catalystListingCommands().yellow
input = LucilleCore::askQuestionAnswerAsString("> ")
CommandInterpreters::catalystListing(input, nil)
