#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

puts CommandInterpreters::catalystCommands().yellow
input = LucilleCore::askQuestionAnswerAsString("> ")
CommandInterpreters::catalyst(input, nil)
