#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

puts "process-Dx33s"
Phage::objects("Dx33").each{|item|
    location = Dx8UnitsUtils::acquireUnitFolderPathOrNull(item["unitId"])
    puts "I am about to garbage collect this location (precaution due to first time): #{location}"
    LucilleCore::pressEnterToContinue()
    LucilleCore::removeFileSystemLocation(location)
}
