#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

puts "DataStore1::propagationLocalDataStore1ToEnergyGridDataStore1()"
DataStore1::propagationLocalDataStore1ToEnergyGridDataStore1()
