#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

exit if ARGV[0].nil? 

uuid = ARGV[0]
object = Librarian::getObjectByUUIDOrNullEnforceUnique(uuid)
if object then
    puts JSON.pretty_generate(object)
    LucilleCore::pressEnterToContinue()
else
    puts "I could not find an object with this uuid"
    LucilleCore::pressEnterToContinue()
end
