#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

puts "StargateUtils::transferDatablobsLocalBufferOutToDatablobsStargateCentralSQLBLobStores()"
StargateUtils::transferDatablobsLocalBufferOutToDatablobsStargateCentralSQLBLobStores()

puts "Infinity Sync"
EventSync::infinityEventsSync()

# We do the following to make sure we have a self contained datablob repository on local
if Machines::isLucille20() then
    puts "File system check"
    FileSystemCheck::fsck()
end