#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

puts "StargateCentralData::propagateData()"
StargateCentralData::propagateData()

puts "Infinity Sync"
EventSync::infinityEventsSync()
