#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

puts "Librarian::maintenance()"
Librarian::maintenance()

puts "StargateCentralData::propagateData()"
StargateCentralData::propagateData()

puts "Infinity Sync"
EventsToCentral::sync()
