#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

StargateCentral::syncDatablobs()
StargateCentral::syncEventLogs()

LibrarianDataCenter::rebuildDatasetsFromScratchUsingEventLog()

if Machines::isLucille20() then
    FileSystemCheck::fsck()
end