#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

# probe system

puts ""
puts "Fx18s:".green
eventuuids = Fx256::eventuuids()
puts "Found #{eventuuids.size} events"
puts "Events collection trace: #{Digest::SHA1.hexdigest(eventuuids.sort.join(":"))}"


puts ""
puts "Bank:".green
eventuuids = Bank::eventuuids()
puts "Found #{eventuuids.size} events"
puts "Events collection trace: #{Digest::SHA1.hexdigest(eventuuids.sort.join(":"))}"

puts ""
puts "ItemToGroupMapping:".green
eventuuids = ItemToGroupMapping::eventuuids()
puts "Found #{eventuuids.size} events"
puts "Events collection trace: #{Digest::SHA1.hexdigest(eventuuids.sort.join(":"))}"

puts ""
puts "NetworkLinks:".green
eventuuids = NetworkLinks::eventuuids()
puts "Found #{eventuuids.size} events"
puts "Events collection trace: #{Digest::SHA1.hexdigest(eventuuids.sort.join(":"))}"
