#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

puts "Nx113Transforms::transformDx8UnitToAionPointsDuringEnergyGridUpdate()"
Nx113Transforms::transformDx8UnitToAionPointsDuringEnergyGridUpdate()
