#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require_relative "load-code.rb"

# --------------------------------------------------------------------

NyxUserInterface::uimainloop()

