#!/usr/bin/ruby

# encoding: UTF-8

require_relative "load-code.rb"

# --------------------------------------------------------------------

puts JSON.generate(NyxPermanodeOperator::timelinesInDecreasingActivityDateTime())
