#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/KeyValueStore.rb"
=begin
    KeyValueStore::setFlagTrue(repositorylocation, key)
    KeyValueStore::setFlagFalse(repositorylocation, key)
    KeyValueStore::flagIsTrue(repositorylocation, key)

    KeyValueStore::set(repositorylocation or nil, key, value)
    KeyValueStore::getOrNull(repositorylocation or nil, key)
    KeyValueStore::getOrDefaultValue(repositorylocation or nil, key, defaultValue)
    KeyValueStore::destroy(repositorylocation or nil, key)
=end

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/Mercury.rb"
=begin
    Mercury::postValue(channel, value)
    Mercury::dequeueFirstValueOrNull(channel)

    Mercury::discardFirstElementsToEnforeQueueSize(channel, size)
    Mercury::discardFirstElementsToEnforceTimeHorizon(channel, unixtime)

    Mercury::getQueueSize(channel)
    Mercury::getAllValues(channel)

    Mercury::getFirstValueOrNull(channel)
    Mercury::deleteFirstValue(channel)
=end

require_relative "Nyx.rb"

# --------------------------------------------------------------------

Mercury::discardFirstElementsToEnforceTimeHorizon("14f50e3a-25f5-4e8b-86c7-71d55b10ee9b", Time.new.to_i - 86400)

size24HoursSize = Mercury::getQueueSize("14f50e3a-25f5-4e8b-86c7-71d55b10ee9b").size

shouldrun = (rand <= Math.exp(-size24HoursSize.to_f/50))

exit if !shouldrun

NyxPermanodeOperator::permanodesEnumerator(NyxEstate::pathToYmir())
    .select{|permanode|
        !KeyValueStore::flagIsTrue(nil, permanode["uuid"]+"E59EC819-693C-4E85-88F5-A3B1B83F7021")
    }
    .first(5)
    .each{ |permanode|
        system("clear")
        puts "Nyx Review (size24HoursSize: #{size24HoursSize})"
        LucilleCore::pressEnterToContinue()
        NyxUserInterface::permanodeDive(permanode)
        KeyValueStore::setFlagTrue(nil, permanode["uuid"]+"E59EC819-693C-4E85-88F5-A3B1B83F7021")
        Mercury::postValue("14f50e3a-25f5-4e8b-86c7-71d55b10ee9b", true) # For throtteling
    }
