#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require_relative "Nyx.rb"

# --------------------------------------------------------------------

puts JSON.generate(NyxPermanodeOperator::permanodesEnumerator(NyxEstate::pathToYmir()).to_a)
