#!/usr/bin/ruby

# encoding: UTF-8

# encoding: UTF-8
require 'json'
# JSON.pretty_generate(object)

require 'date'
require 'colorize'

require 'securerandom'
# SecureRandom.hex    #=> "eb693ec8252cd630102fd0d0fb7c3485"
# SecureRandom.hex(4) #=> "eb693123"
# SecureRandom.uuid   #=> "2d931510-d99f-494a-8c67-87feb05e1594"

require 'fileutils'
# FileUtils.mkpath '/a/b/c'
# FileUtils.cp(src, dst)
# FileUtils.mv 'oldname', 'newname'
# FileUtils.rm(path_to_image)
# FileUtils.rm_rf('dir/to/remove')

require 'digest/sha1'
# Digest::SHA1.hexdigest 'foo'
# Digest::SHA1.file(myFile).hexdigest

require 'find'

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/LucilleCore.rb"

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/KeyValueStore.rb"
=begin
    KeyValueStore::setFlagTrue(repositorylocation or nil, key)
    KeyValueStore::setFlagFalse(repositorylocation or nil, key)
    KeyValueStore::flagIsTrue(repositorylocation or nil, key)

    KeyValueStore::set(repositorylocation or nil, key, value)
    KeyValueStore::getOrNull(repositorylocation or nil, key)
    KeyValueStore::getOrDefaultValue(repositorylocation or nil, key, defaultValue)
    KeyValueStore::destroy(repositorylocation or nil, key)
=end

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/YmirEstate.rb"
=begin
    YmirEstate::ymirFilepathEnumerator(pathToYmir)
    YmirEstate::locationBasenameToYmirLocationOrNull(pathToYmir, basename)
    YmirEstate::makeNewYmirLocationForBasename(pathToYmir, basename)
        # If base name is meant to be the name of a folder then folder itself 
        # still need to be created. Only the parent is created.
=end

require "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Todo/Todo.rb"

require_relative "Starburst.rb"

# --------------------------------------------------------------------

loop {
    system('clear')
    puts "Starburst 💫"
    options = [
        "Dive Folders",
        "New Folder",
        "Collect Desktop location into folder (existing or new)"
    ]
    option = LucilleCore::selectEntityFromListOfEntitiesOrNull("starburst", options)
    break if option.nil?
    if option == "Dive Folders" then
        Starburst::diveStartburstFolders()
    end
    if option == "New Folder" then
        Starburst::interactivelyMakeNewFolderReturnFolderpath()
    end
    if option == "Collect Desktop location into folder (existing or new)" then
        starburstname = Starburst::selectExistingStarburstNameOrMakeANewOneReturnName()
        starburstfolderpath = Starburst::starburstNameToFolderpath(starburstname)
        desktopLocations = LucilleCore::locationsAtFolder("/Users/pascal/Desktop")
                            .select{|filepath| filepath[0,1] != '.' }
                            .sort
        location1 = LucilleCore::selectEntityFromListOfEntitiesOrNull("location", desktopLocations, lambda{ |location| File.basename(location) })
        next if location1.nil?
        name1 = File.basename(location1)
        name2 = "#{(Starburst::maxIndexAtStarburstName(starburstname)+1)}-#{name1}"
        location2 = "#{starburstfolderpath}/#{name2}"
        if File.file?(location1) then
            FileUtils.mv(location1, location2)
        else
            FileUtils.mkdir(location2)
            LucilleCore::copyContents(location1, location2)
        end
    end
}
