#!/usr/bin/ruby

# encoding: UTF-8

require_relative "time-management-service-core.rb"

class Interface

    def start(uid)
        Chronos::start(uid)
    end 

    def isRunning(uid)
        Chronos::isRunning(uid)
    end

    def stopAndAddTimeSpan(uid)
        timespan = Chronos::stop(uid)
        Chronos::addTimespan(uid, timespan)
    end

    def metric(uid, hoursCommitmentPerWeek, metricAtZero, metricRunning)
        Chronos::metric(uid, hoursCommitmentPerWeek, metricAtZero, metricRunning)
    end

    def getEntityAdaptedTotalTimespan(uid)
        Chronos::getEntityAdaptedTotalTimespan(uid)
    end

    def addTimeSpan(uid, timespan)
        Chronos::addTimespan(uid, timespan)
    end
end

DRb.start_service("druby://:10423", Interface.new())
DRb.thread.join

