#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require 'json'
# JSON.pretty_generate(object)

require 'date'
require 'colorize'

require 'securerandom'
# SecureRandom.hex    #=> "eb693ec8252cd630102fd0d0fb7c3485"
# SecureRandom.hex(4) #=> "eb693123"
# SecureRandom.uuid   #=> "2d931510-d99f-494a-8c67-87feb05e1594"

require 'fileutils'
# FileUtils.mkpath '/a/b/c'
# FileUtils.cp(src, dst)
# FileUtils.mv 'oldname', 'newname'
# FileUtils.rm(path_to_image)
# FileUtils.rm_rf('dir/to/remove')

require 'digest/sha1'
# Digest::SHA1.hexdigest 'foo'
# Digest::SHA1.file(myFile).hexdigest

require 'find'

require "/Users/pascal/Galaxy/LucilleOS/Libraries/Ruby-Libraries/LucilleCore.rb"

require "/Users/pascal/Galaxy/LucilleOS/Libraries/Ruby-Libraries/KeyValueStore.rb"
=begin
    KeyValueStore::setFlagTrue(repositorylocation or nil, key)
    KeyValueStore::setFlagFalse(repositorylocation or nil, key)
    KeyValueStore::flagIsTrue(repositorylocation or nil, key)

    KeyValueStore::set(repositorylocation or nil, key, value)
    KeyValueStore::getOrNull(repositorylocation or nil, key)
    KeyValueStore::getOrDefaultValue(repositorylocation or nil, key, defaultValue)
    KeyValueStore::destroy(repositorylocation or nil, key)
=end

require "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Catalyst/DoNotShowUntil.rb"
#    DoNotShowUntil::setUnixtime(uid, unixtime)
#    DoNotShowUntil::isVisible(uid)

require "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Catalyst/Mercury.rb"
=begin
    Mercury::postValue(channel, value)

    Mercury::discardFirstElementsToEnforeQueueSize(channel, size)
    Mercury::discardFirstElementsToEnforceTimeHorizon(channel, unixtime)

    Mercury::getQueueSize(channel)
    Mercury::getAllValues(channel)

    Mercury::getFirstValueOrNull(channel)
    Mercury::deleteFirstValue(channel)
=end

require "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Catalyst/Runner.rb"
=begin 
    Runner::isRunning(uuid)
    Runner::runTimeInSecondsOrNull(uuid) # null | Float
    Runner::start(uuid)
    Runner::stop(uuid) # null | Float
=end

require "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Catalyst/Bank.rb"
=begin 
    Bank::put(uuid, weight)
    Bank::value(uuid)
=end

require_relative "Spaceships.rb"

# -------------------------------------------------------------------------

# Guardian Work
DailyTimes::putTimeToBankNoOftenThanOnceADay("5c81927e-c4fb-4f8d-adae-228c346c8c7d", -6*3600, [1, 2, 3, 4, 5]) # 6 hours, Monday to Friday

# Spaceship bank managed
Spaceships::spaceships()
    .select{|spaceship| ["bank-account"].include?(spaceship["engine"]["type"]) }
    .sort{|i1, i2| i1["creationUnixtime"] <=> i2["creationUnixtime"] }
    .first(3)
    .each{|spaceship|
        DailyTimes::putTimeToBankNoOftenThanOnceADay(spaceship["uuid"], -(2.to_f/3)*3600, [1, 2, 3, 4, 5, 6])
    }

# -------------------------------------------------------------------------

objects = []

Spaceships::spaceships()
    .sort{|i1, i2| i1["creationUnixtime"] <=> i2["creationUnixtime"] }
    .each{|spaceship|

        defaultCommand = lambda {|isRunning|
            isRunning ? "stop" : "start"
        }

        uuid = spaceship["uuid"]
        isRunning = Runner::isRunning(uuid)
        isRunningForLong = (Spaceships::liveRunTimeIfAny(spaceship) > 3600)

        objects << {
            "uuid"           => uuid,
            "application"    => "Spaceships",
            "contentItem"    => {
                "type" => "line",
                "line" => Spaceships::toString(spaceship)
            },
            "metric"         => Spaceships::metric(spaceship),
            "commands"       => ["start", "open", "stop", "description", "destroy"],
            "defaultCommand" => defaultCommand.call(isRunning),
            "isRunning"      => isRunning,
            "isRunningForLong" => isRunningForLong,
            "isDone" => Spaceships::isDone?(spaceship),
            "shell-redirects" => {
                "start"   => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Spaceships/x-catalyst-objects-processing start '#{uuid}'",
                "open"    => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Spaceships/x-catalyst-objects-processing open '#{uuid}'",
                "stop"    => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Spaceships/x-catalyst-objects-processing stop '#{uuid}'",
                "description" => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Spaceships/x-catalyst-objects-processing description '#{uuid}'",
                "destroy" => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Spaceships/x-catalyst-objects-processing destroy '#{uuid}'",
            },
            "x-spaceship"         => spaceship,
            "x-running-for"     => Runner::runTimeInSecondsOrNull(uuid),
            "x-total-live-time" => Spaceships::liveTotalTime(spaceship),
        }
    }

puts JSON.generate(objects)
