#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

# ----------------------------------------------------------------------------

uuid = ARGV[0]
exit if uuid.nil?
object = Librarian6Objects::getObjectByUUIDOrNull(uuid)
if object["mikuType"] != "Nx31" then
    puts "Found an object but it's not a Nx31"
    exit
end
Nx31::landing(object)
