#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

# ----------------------------------------------------------------------------

# This is call from `lucille`

entity = Nx31::interactivelyCreateNewOrNull()
exit if entity.nil?
Nx31::landing(entity)
