#!/usr/bin/ruby

# encoding: UTF-8

require_relative "../Libs/loader.rb"

# ----------------------------------------------------------------------------

# This is called from `lucille`

entity = NyxNetworkNodes::interactivelyCreateNewOrNull()
exit if entity.nil?
NyxNetworkNodes::landing(entity)
