#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require 'json'
# JSON.pretty_generate(object)

require 'fileutils'
# FileUtils.mkpath '/a/b/c'
# FileUtils.cp(src, dst)
# FileUtils.mv 'oldname', 'newname'
# FileUtils.rm(path_to_image)
# FileUtils.rm_rf('dir/to/remove')

require 'securerandom'
# SecureRandom.hex    #=> "eb693ec8252cd630102fd0d0fb7c3485"
# SecureRandom.hex(4) #=> "eb693123"
# SecureRandom.uuid   #=> "2d931510-d99f-494a-8c67-87feb05e1594"

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/LucilleCore.rb"

require_relative "../Catalyst-Common/TheCacheWithLambdas.rb"

require_relative "Lucille.rb"

# -----------------------------------------------------------------------------

if ARGV[0] == "open" and ARGV[1] then
    uuid = ARGV[1]
    exit if !LucilleThisCore::isCurrentUUID(uuid)
    LXUserInterface::bestOpen(uuid)
end

if ARGV[0] == "open+done" and ARGV[1] then
    uuid = ARGV[1]
    exit if !LucilleThisCore::isCurrentUUID(uuid)
    LXUserInterface::bestOpen(uuid)
    LXUserInterface::doneItem(uuid)
end

if ARGV[0] == "edit" and ARGV[1] then
    uuid = ARGV[1]
    exit if !LucilleThisCore::isCurrentUUID(uuid)
    LXUserInterface::editContent(uuid)
    TheCacheWithLambdas::invalidate("FC36D82E-77E2-4B2C-B3A7-23BDC7A7C441")
end

if ARGV[0] == "set-description" and ARGV[1] then
    uuid = ARGV[1]
    exit if !LucilleThisCore::isCurrentUUID(uuid)
    text = LucilleThisCore::getDescription(uuid)
    text = CatalystCommon::editTextUsingTextmate(text)
    LucilleThisCore::setDescription(uuid, text)
    TheCacheWithLambdas::invalidate("FC36D82E-77E2-4B2C-B3A7-23BDC7A7C441")
end

if ARGV[0] == "recast" and ARGV[1] then
    uuid = ARGV[1]
    exit if !LucilleThisCore::isCurrentUUID(uuid)
    LXUserInterface::recastItem(uuid)
    TheCacheWithLambdas::invalidate("FC36D82E-77E2-4B2C-B3A7-23BDC7A7C441")
end

if ARGV[0] == "done" and ARGV[1] then
    uuid = ARGV[1]
    exit if !LucilleThisCore::isCurrentUUID(uuid)
    LXUserInterface::doneItem(uuid)

    # -----------------------------------------------------------------------
    # mark: be89bcf6-3bae-4872-ad1b-ea882aceddda
    # TheCacheWithLambdas::invalidate("FC36D82E-77E2-4B2C-B3A7-23BDC7A7C441")
    # We no longer invalidate the precomputed catalyst objects when one is done
    # Instead, we remove the corresponding object from the precomputed data
    # -----------------------------------------------------------------------
end

if ARGV[0] == "to-nyx" then
    uuid = ARGV[1]
    exit if !LucilleThisCore::isCurrentUUID(uuid)
    LucilleThisCore::recastAsNyxItem(uuid)
    TheCacheWithLambdas::invalidate("FC36D82E-77E2-4B2C-B3A7-23BDC7A7C441")
    exit
end

if ARGV[0] == "to-ifcs" and ARGV[1] then
    uuid = ARGV[1]
    puts uuid
    exit if !LucilleThisCore::isCurrentUUID(uuid)
    LucilleThisCore::recastAsIFCSItem(uuid)
    TheCacheWithLambdas::invalidate("FC36D82E-77E2-4B2C-B3A7-23BDC7A7C441")
end
