#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require 'json'
# JSON.pretty_generate(object)

require 'fileutils'
# FileUtils.mkpath '/a/b/c'
# FileUtils.cp(src, dst)
# FileUtils.mv 'oldname', 'newname'
# FileUtils.rm(path_to_image)
# FileUtils.rm_rf('dir/to/remove')

require 'securerandom'
# SecureRandom.hex    #=> "eb693ec8252cd630102fd0d0fb7c3485"
# SecureRandom.hex(4) #=> "eb693123"
# SecureRandom.uuid   #=> "2d931510-d99f-494a-8c67-87feb05e1594"

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/LucilleCore.rb"

# --------------------------------------------------------------------

require_relative "Lucille.rb"

# -----------------------------------------------------------------------------

if ARGV[0] == "open" and ARGV[1] then
    uuid = ARGV[1]
    aetherfilepath = LucilleThisCore::uuid2aetherfilepath(uuid)
    exit if !File.exists?(aetherfilepath)
    LXUserInterface::openItemReadOnly(uuid)
end

if ARGV[0] == "set-description" and ARGV[1] then
    uuid = ARGV[1]
    aetherfilepath = LucilleThisCore::uuid2aetherfilepath(uuid)
    exit if !File.exists?(aetherfilepath)
    description = LucilleCore::askQuestionAnswerAsString("description: ")
    LucilleThisCore::setDescription(uuid, description)
end

if ARGV[0] == "recast" and ARGV[1] then
    uuid = ARGV[1]
    aetherfilepath = LucilleThisCore::uuid2aetherfilepath(uuid)
    exit if !File.exists?(aetherfilepath)
    LXUserInterface::recastItem(uuid)
end

if ARGV[0] == "done" and ARGV[1] then
    uuid = ARGV[1]
    aetherfilepath = LucilleThisCore::uuid2aetherfilepath(uuid)
    exit if !File.exists?(aetherfilepath)
    LXUserInterface::doneItem(uuid)
end

if ARGV[0] == ">nyx" then
    uuid = ARGV[1]
    aetherfilepath = LucilleThisCore::uuid2aetherfilepath(uuid)
    exit if !File.exists?(aetherfilepath)
    LucilleThisCore::transformIntoNyxItem(uuid)
    exit
end

if ARGV[0] == ">ifcs" and ARGV[1] then
    uuid = ARGV[1]
    aetherfilepath = LucilleThisCore::uuid2aetherfilepath(uuid)
    exit if !File.exists?(aetherfilepath)
end
