#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require 'json'
# JSON.pretty_generate(object)

require 'date'
require 'colorize'

require 'securerandom'
# SecureRandom.hex    #=> "eb693ec8252cd630102fd0d0fb7c3485"
# SecureRandom.hex(4) #=> "eb693123"
# SecureRandom.uuid   #=> "2d931510-d99f-494a-8c67-87feb05e1594"

require 'fileutils'
# FileUtils.mkpath '/a/b/c'
# FileUtils.cp(src, dst)
# FileUtils.mv 'oldname', 'newname'
# FileUtils.rm(path_to_image)
# FileUtils.rm_rf('dir/to/remove')

require 'digest/sha1'
# Digest::SHA1.hexdigest 'foo'
# Digest::SHA1.file(myFile).hexdigest

require 'find'

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/LucilleCore.rb"

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/KeyValueStore.rb"
=begin
    KeyValueStore::setFlagTrue(repositorylocation or nil, key)
    KeyValueStore::setFlagFalse(repositorylocation or nil, key)
    KeyValueStore::flagIsTrue(repositorylocation or nil, key)

    KeyValueStore::set(repositorylocation or nil, key, value)
    KeyValueStore::getOrNull(repositorylocation or nil, key)
    KeyValueStore::getOrDefaultValue(repositorylocation or nil, key, defaultValue)
    KeyValueStore::destroy(repositorylocation or nil, key)
=end

require_relative "Lucille.rb"

# -------------------------------------------------------------------------

LucilleThisCore::ensureStandardFilenames()

# -------------------------------------------------------------------------

def makeContentItem(location, timeline)
    # We have the two special timelines [Inbox] and [Infinity]
    timelinefragment = timeline[0, 1] == "[" ? timeline : "(#{timeline})"
    if location[-4, 4] == ".txt" then
        return {
            "type" => "line-and-body",
            "line" => "[lucille] #{timelinefragment} #{LucilleThisCore::getBestDescription(location)}",
            "body" => "[lucille] #{timelinefragment} #{(IO.read(location).strip.lines.to_a.size > 1 ? "\n" : "")}#{IO.read(location).strip}"
        }
    end
    {
        "type" => "line",
        "line" => "[lucille] #{timelinefragment} #{LucilleThisCore::getBestDescription(location)}"
    }
end

def makeMetric(location, indx, isRunning, timeline)
    if isRunning then
        return 1
    end

    getDayCachedOrComputedAndCacheMetric = lambda {|location, metric|
        metric = KeyValueStore::getOrNull(nil, "#{Time.new.to_s[0, 10]}:4298a5d7-d24c-4716-b988-eec8d06ccde1:#{location}")
        if metric then
            return metric.to_f
        end
        KeyValueStore::set(nil, "#{Time.new.to_s[0, 10]}:4298a5d7-d24c-4716-b988-eec8d06ccde1:#{location}", metric)
        metric
    }

    if timeline == "[Inbox]" then
        return getDayCachedOrComputedAndCacheMetric.call(location, 0.72 - indx.to_f/1000 )
    end

    return getDayCachedOrComputedAndCacheMetric.call(location, 0.40 - indx.to_f/1000 )
end

def makeCommands(location, timeline)
    runCommands = InFlightControlSystem::isRegistered(location) ? ["start", "stop"] : []
    runCommands + ["open", "done", "set-description", "export-to-desktop", "recast", ">ifcs", ">lucille-other", ">nyx"]
end

def shouldOpenAndDone(location)
    str1 = "vienna-url.txt"
    return true if location[-str1.size, str1.size] == str1
    false
end

def makeDefaultCommand(location, isRunning, timeline)
    if InFlightControlSystem::isRegistered(location) then
        return ( isRunning ? "stop" : "start+open" )
    end
    shouldOpenAndDone(location) ? "open+done" : "open"
end

# -------------------------------------------------------------------------

locations = LucilleThisCore::getTimelineLocations("[Inbox]") + LXCluster::getWorkingCluster()

objects = locations
            .select{|location| DoNotShowUntil::isVisible(location) }
            .map
            .with_index{|location, indx|
                timeline = LucilleThisCore::getLocationTimeline(location)
                uuid = Digest::SHA1.hexdigest(location)
                isRunning = InFlightControlSystem::isRunning(location)
                object = {
                    "uuid"            => uuid,
                    "contentItem"     => makeContentItem(location, timeline),
                    "metric"          => makeMetric(location, indx, isRunning, timeline),
                    "commands"        => makeCommands(location, timeline),
                    "isRunning"       => isRunning,
                    "defaultCommand"  => makeDefaultCommand(location, isRunning, timeline),
                    "shell-redirects" => {
                        "start" => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Lucille/catalyst-objects-processing start '#{location}'",
                        "start+open" => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Lucille/catalyst-objects-processing start+open '#{location}'",
                        "stop" => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Lucille/catalyst-objects-processing stop '#{location}'",
                        "open" => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Lucille/catalyst-objects-processing open '#{location}'",
                        "open+done" => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Lucille/catalyst-objects-processing open+done '#{location}'",
                        "set-description" => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Lucille/catalyst-objects-processing set-description '#{location}'",
                        "recast" => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Lucille/catalyst-objects-processing recast '#{location}'",
                        ">nyx" => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Lucille/catalyst-objects-processing move-to-nyx '#{location}'",
                        "done" => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Lucille/catalyst-objects-processing done '#{location}'",
                        "export-to-desktop" => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Lucille/catalyst-objects-processing export-to-desktop '#{location}'",
                        ">lucille-other" => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Lucille/catalyst-objects-processing merge-with-other-Lucille-location '#{location}'",
                        ">ifcs" => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Lucille/catalyst-objects-processing throttle '#{location}'"
                    },
                    "location"        => location
                }
                InFlightControlSystem::catalistItemIFCSTransmutation(location, object)
            }

puts JSON.generate(objects)
