#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require 'json'
# JSON.pretty_generate(object)

require 'date'
require 'colorize'

require 'securerandom'
# SecureRandom.hex    #=> "eb693ec8252cd630102fd0d0fb7c3485"
# SecureRandom.hex(4) #=> "eb693123"
# SecureRandom.uuid   #=> "2d931510-d99f-494a-8c67-87feb05e1594"

require 'fileutils'
# FileUtils.mkpath '/a/b/c'
# FileUtils.cp(src, dst)
# FileUtils.mv 'oldname', 'newname'
# FileUtils.rm(path_to_image)
# FileUtils.rm_rf('dir/to/remove')

require 'digest/sha1'
# Digest::SHA1.hexdigest 'foo'
# Digest::SHA1.file(myFile).hexdigest

require 'find'

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/LucilleCore.rb"

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/KeyValueStore.rb"
=begin
    KeyValueStore::setFlagTrue(repositorylocation or nil, key)
    KeyValueStore::setFlagFalse(repositorylocation or nil, key)
    KeyValueStore::flagIsTrue(repositorylocation or nil, key)

    KeyValueStore::set(repositorylocation or nil, key, value)
    KeyValueStore::getOrNull(repositorylocation or nil, key)
    KeyValueStore::getOrDefaultValue(repositorylocation or nil, key, defaultValue)
    KeyValueStore::destroy(repositorylocation or nil, key)
=end

require_relative "Lucille.rb"

# -------------------------------------------------------------------------

Lucille::garbageCollection()
Lucille::ensurel22Filenames()

# -------------------------------------------------------------------------

class MetricHelper
    def initialize()
        @counter = 0
    end
    def metric(base)
        @counter = @counter + 1
        base - @counter.to_f/100000
    end
end

def makeContentItem(location, timeline)
    {
        "type" => "line",
        "line" => "[lucille] #{File.basename(location)}#{timeline == "[Inbox]" ? " [Inbox]" : " (#{timeline})"}"
    }
end

def makeMetric(metricHelper, isRunning, timeline)
    if isRunning then
        return 0.74
    end
    if timeline == "[Inbox]" then
        return metricHelper.metric(0.5) # Lucille 'Inbox'
    end
    metricHelper.metric(0.4) # Lucille (timelines)
end

def getCurrentTimelineOrNull()
    timelines = Lucille::timelines()
    return nil if timelines.empty?
    return "[Inbox]" if timelines.include?("[Inbox]")
    indx = ((Time.new.to_f/(3600*2)).to_i) % timelines.size
    timelines[indx]
end

# -------------------------------------------------------------------------

timelinecurrent = getCurrentTimelineOrNull()

metricHelper = MetricHelper.new()

objects = Lucille::locations()
    .select{|location| Lucille::getTimeline(location) == timelinecurrent }
    .map{|location|
        timeline = Lucille::getTimeline(location)
        uuid = Digest::SHA1.hexdigest(location)
        isRunning = Lucille::isLocationRunning(location)
        {
            "uuid"            => uuid,
            "contentItem"     => makeContentItem(location, timeline),
            "metric"          => makeMetric(metricHelper, isRunning, timeline),
            "commands"        => ["open", "[]", "->", "done"],
            "isRunning"       => isRunning,
            "shell-redirects" => {
                "open"  => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Lucille/catalyst-objects-processing open '#{location}'",
                "[]"    => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Lucille/catalyst-objects-processing apply-next-to-text '#{location}'",
                "done"  => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Lucille/catalyst-objects-processing done '#{location}'"
            }
        }
    }

puts JSON.generate(objects)
