#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require 'json'
# JSON.pretty_generate(object)

require 'date'
require 'colorize'

require 'securerandom'
# SecureRandom.hex    #=> "eb693ec8252cd630102fd0d0fb7c3485"
# SecureRandom.hex(4) #=> "eb693123"
# SecureRandom.uuid   #=> "2d931510-d99f-494a-8c67-87feb05e1594"

require 'fileutils'
# FileUtils.mkpath '/a/b/c'
# FileUtils.cp(src, dst)
# FileUtils.mv 'oldname', 'newname'
# FileUtils.rm(path_to_image)
# FileUtils.rm_rf('dir/to/remove')

require 'digest/sha1'
# Digest::SHA1.hexdigest 'foo'
# Digest::SHA1.file(myFile).hexdigest

require 'find'

require "/Users/pascal/Galaxy/LucilleOS/Libraries/Ruby-Libraries/LucilleCore.rb"

require "/Users/pascal/Galaxy/LucilleOS/Libraries/Ruby-Libraries/KeyValueStore.rb"
=begin
    KeyValueStore::setFlagTrue(repositorylocation or nil, key)
    KeyValueStore::setFlagFalse(repositorylocation or nil, key)
    KeyValueStore::flagIsTrue(repositorylocation or nil, key)

    KeyValueStore::set(repositorylocation or nil, key, value)
    KeyValueStore::getOrNull(repositorylocation or nil, key)
    KeyValueStore::getOrDefaultValue(repositorylocation or nil, key, defaultValue)
    KeyValueStore::destroy(repositorylocation or nil, key)
=end

require "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Catalyst/Ping.rb"
=begin 
    Ping::put(uuid, weight)
    Ping::total24hours(uuid)
    Ping::totalToday(uuid)
=end

require_relative "VideoStream.rb"

# -------------------------------------------------------------------------

loop {
    break if VideoStream::videoFolderpathsAtFolder(VideoStream::spaceFolderpath()).size >= 40
    break if VideoStream::videoFolderpathsAtFolder(VideoStream::energyGridFolderpath()).size == 0
    filepath = VideoStream::videoFolderpathsAtFolder(VideoStream::energyGridFolderpath()).first
    filename = File.basename(filepath)
    targetFilepath = "#{VideoStream::spaceFolderpath()}/#{filename}"
    FileUtils.mv(filepath, targetFilepath)
    break if !File.exists?(targetFilepath)
}

if !File.exists?(VideoStream::spaceFolderpath()) then
    puts "[]"
    exit
end

def metric(indx)
    0.60 - indx.to_f/1000 - (0.4/25)*Ping::total24hours("VideoStream-3623a0c2-ef0d-47e2-9008-3c1a9fd52c01") # We go down by 0.4 after 25, we do over 24 hours
end

objects = []

VideoStream::videoFolderpathsAtFolder(VideoStream::spaceFolderpath())
.first(3)
.map
.with_index{|filepath, indx|
    uuid = VideoStream::filepathToVideoUUID(filepath)
    objects << {
        "uuid"           => uuid,
        "application"    => "VideoStream",
        "contentItem"    => {
            "type" => "line",
            "line" => "[VideoStream] #{File.basename(filepath)}"
        },
        "metric"         => metric(indx),
        "commands"       => ["delete"],
        "defaultCommand" => "play",
        "shell-redirects" => {
            "play"   => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/VideoStream/x-catalyst-objects-processing play '#{uuid}'",
            "delete" => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/VideoStream/x-catalyst-objects-processing delete '#{uuid}'"
        }
    }
}

puts JSON.generate(objects)

