#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require 'json'
# JSON.pretty_generate(object)

require 'fileutils'
# FileUtils.mkpath '/a/b/c'
# FileUtils.cp(src, dst)
# FileUtils.mv 'oldname', 'newname'
# FileUtils.rm(path_to_image)
# FileUtils.rm_rf('dir/to/remove')

require "/Users/pascal/Galaxy/LucilleOS/Libraries/Ruby-Libraries/LucilleCore.rb"

require "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Catalyst/Ping.rb"
=begin 
    Ping::put(uuid, weight)
    Ping::totalOverTimespan(uuid, timespanInSeconds)
    Ping::totalToday(uuid)
=end

require_relative "VideoStream.rb"

# -----------------------------------------------------------------------------

if ARGV[0] == "play" then
    uuid = ARGV[1]
    exit if uuid.nil?
    filepath = VideoStream::getVideoFilepathByUUIDOrNull(uuid)
    exit if filepath.nil?
    puts filepath
    if filepath.include?("'") then
        filepath2 = filepath.gsub("'", ',')
        FileUtils.mv(filepath, filepath2)
        filepath = filepath2
    end
    system("open '#{filepath}'")
    if LucilleCore::askQuestionAnswerAsBoolean("-> completed? ", true) then
        FileUtils.rm(filepath)
        sleep 1
    end
    puts "Sending ping unit"
    Ping::put("VideoStream-3623a0c2-ef0d-47e2-9008-3c1a9fd52c01", 1)
end

if ARGV[0] == "completed" then
    uuid = ARGV[1]
    exit if uuid.nil?
    filepath = VideoStream::getVideoFilepathByUUIDOrNull(uuid)
    exit if filepath.nil?
    puts filepath
    FileUtils.rm(filepath)
    puts "Sending ping unit"
    Ping::put("VideoStream-3623a0c2-ef0d-47e2-9008-3c1a9fd52c01", 1)
end
