#!/usr/bin/ruby

# encoding: UTF-8

require 'json'
# JSON.pretty_generate(object)

require 'date'
require 'colorize'
require 'securerandom'
# SecureRandom.hex    #=> "eb693ec8252cd630102fd0d0fb7c3485"
# SecureRandom.hex(4) #=> "eb693123"
# SecureRandom.uuid   #=> "2d931510-d99f-494a-8c67-87feb05e1594"

require 'time'

require 'fileutils'
# FileUtils.mkpath '/a/b/c'
# FileUtils.cp(src, dst)
# FileUtils.mv 'oldname', 'newname'
# FileUtils.rm(path_to_image)
# FileUtils.rm_rf('dir/to/remove')

require 'digest/sha1'
# Digest::SHA1.hexdigest 'foo'
# Digest::SHA1.file(myFile).hexdigest

require 'find'
require 'drb/drb'
require 'thread'

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/LucilleCore.rb"

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/KeyValueStore.rb"
=begin
    KeyValueStore::setFlagTrue(repositorylocation or nil, key)
    KeyValueStore::setFlagFalse(repositorylocation or nil, key)
    KeyValueStore::flagIsTrue(repositorylocation or nil, key)

    KeyValueStore::set(repositorylocation or nil, key, value)
    KeyValueStore::getOrNull(repositorylocation or nil, key)
    KeyValueStore::getOrDefaultValue(repositorylocation or nil, key, defaultValue)
    KeyValueStore::destroy(repositorylocation or nil, key)
=end

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/BTreeSets.rb"
=begin
    BTreeSets::values(repositorylocation or nil, setuuid: String): Array[Value]
    BTreeSets::set(repositorylocation or nil, setuuid: String, valueuuid: String, value)
    BTreeSets::getOrNull(repositorylocation or nil, setuuid: String, valueuuid: String): nil | Value
    BTreeSets::destroy(repositorylocation, setuuid: String, valueuuid: String)
=end

# --------------------------------------------------------------------

require_relative "Library.rb"

# -----------------------------------------------------------------------------

if ARGV[0] == "run" and ARGV[1] then
    uuid = ARGV[1]
    tnode = CoreData::getTNodeByUUIDOrNull(uuid)
    if tnode.nil? then
        puts "Could not find tnode with uuid: '#{uuid}'"
        LucilleCore::pressEnterToContinue()
        exit
    end
    puts Interface::targetToString(tnode["targets"][0])

    startTime = Time.new.to_i

    Interface::optimizedOpenTNodeUniqueTargetOrNothing(tnode)
    operations = ["done", "reclassify", "transmute to nyx"]
    operation = LucilleCore::selectEntityFromListOfEntitiesOrNull("operation", operations)
    if operation == "done" then
        Estate::destroyTNode(tnode)
    end
    if operation == "reclassify" then
        timeline = TMakers::interactively2SelectOneTimelinePossiblyNew(CoreData::timelinesInIncreasingActivityTime().reverse)
        tnode["classification"] = [{
            "uuid"     => SecureRandom.uuid,
            "type"     => "timeline-329D3ABD",
            "timeline" => timeline
        }]
        puts JSON.pretty_generate(tnode)
        Estate::commitTNodeToDisk(Todo::pathToYmir(), tnode)
    end
    if operation == "transmute to nyx" then
        pathToNyxYmirFolder = "/Users/pascal/Galaxy/Nyx"
        nyxItem = TodoNyxConverter::transmuteTodoItemIntoNyxObject(tnode, Todo::pathToYmir(), pathToNyxYmirFolder)
        filename = "#{Utils::l22()}.json"
        filepath = YmirEstate::makeNewYmirLocationForBasename(pathToNyxYmirFolder, filename)
        puts JSON.pretty_generate(nyxItem)
        File.open(filepath, "w"){|f| f.puts(JSON.pretty_generate(nyxItem)) }
        Estate::destroyTNode(tnode)
    end

    timeline = tnode["classification"][0]["timeline"]
    timespan = Time.new.to_i - startTime
    point = {
        "uuid"     => SecureRandom.uuid,
        "unixtime" => Time.new.to_i,
        "timeline" => timeline,
        "timespan" => timespan
    }
    puts "Timeline activity point:"
    puts JSON.pretty_generate(point)
    BTreeSets::set(WALKS_DATASTORE_FOLDERPATH, WALKS_SETUUID1, point["uuid"], point)

end

if ARGV[0] == "recast" and ARGV[1] then
    uuid = ARGV[1]
    tnode = CoreData::getTNodeByUUIDOrNull(uuid)
    if tnode.nil? then
        puts "Could not find tnode with uuid: '#{uuid}'"
        LucilleCore::pressEnterToContinue()
        exit
    end
    puts Interface::targetToString(tnode["targets"][0])

    timeline = TMakers::interactively2SelectOneTimelinePossiblyNew(CoreData::timelinesInIncreasingActivityTime().reverse)
    tnode["classification"] = [{
        "uuid"     => SecureRandom.uuid,
        "type"     => "timeline-329D3ABD",
        "timeline" => timeline
    }]
    puts JSON.pretty_generate(tnode)
    Estate::commitTNodeToDisk(Todo::pathToYmir(), tnode)

end

if ARGV[0] == "tonyx" and ARGV[1] then
    uuid = ARGV[1]
    tnode = CoreData::getTNodeByUUIDOrNull(uuid)
    if tnode.nil? then
        puts "Could not find tnode with uuid: '#{uuid}'"
        LucilleCore::pressEnterToContinue()
        exit
    end
    puts Interface::targetToString(tnode["targets"][0])
    pathToNyxYmirFolder = "/Users/pascal/Galaxy/Nyx"
    nyxItem = TodoNyxConverter::transmuteTodoItemIntoNyxObject(tnode, Todo::pathToYmir(), pathToNyxYmirFolder)
    filename = "#{Utils::l22()}.json"
    filepath = YmirEstate::makeNewYmirLocationForBasename(pathToNyxYmirFolder, filename)
    puts JSON.pretty_generate(nyxItem)
    File.open(filepath, "w"){|f| f.puts(JSON.pretty_generate(nyxItem)) }
    Estate::destroyTNode(tnode)
end
