#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require 'json'
# JSON.pretty_generate(object)

require 'date'
require 'colorize'
require 'securerandom'
# SecureRandom.hex    #=> "eb693ec8252cd630102fd0d0fb7c3485"
# SecureRandom.hex(4) #=> "eb693123"
# SecureRandom.uuid   #=> "2d931510-d99f-494a-8c67-87feb05e1594"

require 'time'

require 'fileutils'
# FileUtils.mkpath '/a/b/c'
# FileUtils.cp(src, dst)
# FileUtils.mv 'oldname', 'newname'
# FileUtils.rm(path_to_image)
# FileUtils.rm_rf('dir/to/remove')

require 'digest/sha1'
# Digest::SHA1.hexdigest 'foo'
# Digest::SHA1.file(myFile).hexdigest

require 'find'
require 'thread'

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/LucilleCore.rb"

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/KeyValueStore.rb"
=begin
    KeyValueStore::setFlagTrue(repositorylocation or nil, key)
    KeyValueStore::setFlagFalse(repositorylocation or nil, key)
    KeyValueStore::flagIsTrue(repositorylocation or nil, key)

    KeyValueStore::set(repositorylocation or nil, key, value)
    KeyValueStore::getOrNull(repositorylocation or nil, key)
    KeyValueStore::getOrDefaultValue(repositorylocation or nil, key, defaultValue)
    KeyValueStore::destroy(repositorylocation or nil, key)
=end

# --------------------------------------------------------------------

require_relative "Todo.rb"

# --------------------------------------------------------------------

# We start by collecting the objects in the Inbox

Dir.entries(Todo::pathToTodoInbox())
    .select{|filename| filename[-8, 8] == ".url.txt" }
    .each{|filename|
        filepath = "#{Todo::pathToTodoInbox()}/#{filename}"
        link = IO.read(filepath).strip
        target = {
            "uuid" => SecureRandom.uuid,
            "type" => "url-EFB8D55B",
            "url"  => link
        }
        classificationItem = {
            "uuid"     => SecureRandom.uuid,
            "type"     => "timeline-329D3ABD",
            "timeline" => Todo::todoInboxTimelineName()
        }
        tnode = {
            "uuid"              => SecureRandom.uuid,
            "filename"          => "#{TodoXUtils::l22()}.zeta",
            "creationTimestamp" => Time.new.to_f,
            "description"       => link,
            "targets"           => [ target ],
            "classification"    => [ classificationItem ]
        }
        TodoXEstate::firstTimeCommitTNodeToDisk(tnode)
        FileUtils.rm(filepath)
    }

Dir.entries(Todo::pathToTodoInbox())
    .select{|filename| filename[-9, 9] == ".text.txt" }
    .each{|filename|
        filepath = "#{Todo::pathToTodoInbox()}/#{filename}"
        text = IO.read(filepath).strip
        if text == "" then
            FileUtils.rm(filepath)
            next
        end
        if text.lines.to_a.size == 1 then
            line = text
            target = {
                "uuid" => SecureRandom.uuid,
                "type" => "line-2A35BA23",
                "line" => line
            }
            classificationItem = {
                "uuid"     => SecureRandom.uuid,
                "type"     => "timeline-329D3ABD",
                "timeline" => Todo::todoInboxTimelineName()
            }
            tnode = {
                "uuid"              => SecureRandom.uuid,
                "filename"          => "#{TodoXUtils::l22()}.zeta",
                "creationTimestamp" => Time.new.to_f,
                "description"       => text.lines.to_a.first.strip,
                "targets"           => [ target ],
                "classification"    => [ classificationItem ]
            }
            TodoXEstate::firstTimeCommitTNodeToDisk(tnode)
            FileUtils.rm(filepath)
        end
        if text.lines.to_a.size > 1 then
            target = {
                "uuid"     => SecureRandom.uuid,
                "type"     => "text-A9C3641C",
                "zetaKey"  => SecureRandom.uuid
            }
            classificationItem = {
                "uuid"     => SecureRandom.uuid,
                "type"     => "timeline-329D3ABD",
                "timeline" => Todo::todoInboxTimelineName()
            }
            tnode = {
                "uuid"              => SecureRandom.uuid,
                "filename"          => "#{TodoXUtils::l22()}.zeta",
                "creationTimestamp" => Time.new.to_f,
                "description"       => text.lines.to_a.first.strip,
                "targets"           => [ target ],
                "classification"    => [ classificationItem ]
            }
            TodoXEstate::firstTimeCommitTNodeToDisk(tnode)
            TodoXEstate::setKVAtZetaFileIdentifiedByTNodeUUID(tnode["uuid"], target["zetaKey"], text)
            FileUtils.rm(filepath)
        end
    }

TodoXWalksCore::remove2FromDataset1ThePointsWithObsoleteTimelines()
TodoXWalksCore::limit2SizeOfDataset1()

# --------------------------------------------------------------------

class MetricHelper
    def initialize(base)
        @base = base
        @counter = 0
    end
    def metric()
        @counter = @counter + 1
        @base - @counter.to_f/1000
    end
end

metricHelper = MetricHelper.new(0.70)

objects = []

tnodes = TodoXEstate::getTNodes()

TodoXCoreData::getTimelineTNodesOrdered(tnodes, Todo::todoInboxTimelineName()).each{|tnode|
    objects << {
        "uuid"            => tnode["uuid"],
        "agentuid"        => nil,
        "contentItem"     => {
            "type" => "line",
            "line" => "todo [inbox]: " + tnode["description"] # TodoXUserInterface::targetToString(tnode["targets"][0])
        },
        "metric"          => metricHelper.metric(),
        "commands"        => ["run", "recast", "tonyx"],
        "defaultCommand"  => "run",
        "isDone"          => nil,
        "shell-redirects" => {
            "run"    => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Todo/catalyst-objects-processing run '#{tnode["uuid"]}'",
            "recast" => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Todo/catalyst-objects-processing recast '#{tnode["uuid"]}'",
            "tonyx"  => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Todo/catalyst-objects-processing tonyx '#{tnode["uuid"]}'"
        }
    }
}

metricHelper = MetricHelper.new(0.30)

timeline = TodoXWalksCore::get2TimelineWithLowestTimespan(TodoXWalksCore::get3TNodesTimelines(tnodes), TodoXWalksCore::timeline2TimeMapping())

tnodes
    .select{|tnode|
        tnode["classification"][0]["timeline"] == timeline
    }
    .sort{|tnode1, tnode2|
        tnode1["creationTimestamp"] <=> tnode2["creationTimestamp"]
    }
    .each{|tnode|
        objects << {
            "uuid"           => tnode["uuid"],
            "agentuid"       => nil,
            "contentItem"    => {
                "type" => "line",
                "line" => "todo walk @ #{timeline} / " + TodoXUserInterface::targetToString(tnode["targets"][0])
            },
            "metric"         => metricHelper.metric(),
            "commands"        => ["run", "recast", "tonyx"],
            "defaultCommand"  => "run",
            "isDone"         => nil,
            "shell-redirects" => {
                "run"    => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Todo/catalyst-objects-processing run '#{tnode["uuid"]}'",
                "recast" => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Todo/catalyst-objects-processing recast '#{tnode["uuid"]}'",
                "tonyx"  => "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Todo/catalyst-objects-processing tonyx '#{tnode["uuid"]}'"
            }
        }
    }

puts JSON.generate(objects)

