#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require 'find'

require 'json'
# JSON.pretty_generate

require 'time'

require 'colorize'

require 'fileutils'
# FileUtils.mkpath '/a/b/c'
# FileUtils.cp(src, dst)
# FileUtils.mv 'oldname', 'newname'
# FileUtils.rm(path_to_image)
# FileUtils.rm_rf('dir/to/remove')

require 'securerandom'
# SecureRandom.hex    #=> "eb693ec8252cd630102fd0d0fb7c3485"
# SecureRandom.hex(5) #=> "eb693"
# SecureRandom.uuid   #=> "2d931510-d99f-494a-8c67-87feb05e1594"

require "/Users/pascal/Galaxy/LucilleOS/Libraries/Ruby-Libraries/LucilleCore.rb"
# LucilleCore::askQuestionAnswerAsString(question)
# LucilleCore::askQuestionAnswerAsBoolean(announce, defaultValue = nil)

require "/Users/pascal/Galaxy/LucilleOS/Libraries/Ruby-Libraries/KeyValueStore.rb"
=begin
    KeyValueStore::setFlagTrue(repositorylocation, key)
    KeyValueStore::setFlagFalse(repositorylocation, key)
    KeyValueStore::flagIsTrue(repositorylocation, key)

    KeyValueStore::set(repositorylocation or nil, key, value)
    KeyValueStore::getOrNull(repositorylocation or nil, key)
    KeyValueStore::getOrDefaultValue(repositorylocation or nil, key, defaultValue)
    KeyValueStore::destroy(repositorylocation or nil, key)
=end

require "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Catalyst/Quark.rb"

require "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Catalyst/Bank.rb"
=begin 
    Bank::put(uuid, weight)
    Bank::value(uuid)
=end

require_relative "Todo.rb"

# --------------------------------------------------------------------

loop {
    system("clear")
    puts "Todo 👩‍💻"
    options = [
        "create new item",
        "projects dive",
        "time report"
    ]
    option = LucilleCore::selectEntityFromListOfEntitiesOrNull("operation", options)
    break if option.nil?
    if option == "create new item" then
        target = Quark::issueNewQuarkInteractivelyOrNull()
        next if target.nil?
        projectname = Todo::selectProjectNameInteractivelyOrNull()
        projectuuid = nil
        if projectname.nil? then
            projectname = LucilleCore::askQuestionAnswerAsString("project name: ")
            projectuuid = SecureRandom.uuid
        else
            projectuuid = Todo::projectname2projectuuidOrNUll(projectname)
            # We are not considering the case null
        end
        description = LucilleCore::askQuestionAnswerAsString("todo item description: ")
        item = Todo::issueNewItem(projectname, projectuuid, description, target)
        puts JSON.pretty_generate(item)
    end
    if option == "projects dive" then
        loop {
            puts "-> Todo items dive"
            projectname = LucilleCore::selectEntityFromListOfEntitiesOrNull("project name", Todo::projectNames())
            break if projectname.nil?
            loop {
                puts "-> Visiting project '#{projectname}'"
                items = Todo::itemsForProjectName(projectname)
                break if items.empty? # happens when we loop bacl if the one item of the project was deleted
                item = LucilleCore::selectEntityFromListOfEntitiesOrNull("item", items, lambda{|item| Todo::itemToString(item) })
                break if item.nil?
                Todo::diveItem(item)
            }
        }
    end
    if option == "time report" then
        items = Todo::projectsTimeDistribution()
        d = items.map{|item| item["projectname"].size }.max
        items
            .sort{|i1, i2| i1["timeInHours"] <=> i2["timeInHours"] }
            .each{|item|
                puts "#{item["projectname"].ljust(d+1)} #{"%8.2f" % item["timeInHours"]} hours"
            }
        LucilleCore::pressEnterToContinue()
    end
}
