#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require 'json'
# JSON.pretty_generate(object)

require 'fileutils'
# FileUtils.mkpath '/a/b/c'
# FileUtils.cp(src, dst)
# FileUtils.mv 'oldname', 'newname'
# FileUtils.rm(path_to_image)
# FileUtils.rm_rf('dir/to/remove')

require "/Users/pascal/Galaxy/LucilleOS/Libraries/Ruby-Libraries/LucilleCore.rb"

require "/Users/pascal/Galaxy/LucilleOS/Libraries/Ruby-Libraries/KeyValueStore.rb"
=begin
    KeyValueStore::setFlagTrue(repositorylocation or nil, key)
    KeyValueStore::setFlagFalse(repositorylocation or nil, key)
    KeyValueStore::flagIsTrue(repositorylocation or nil, key)

    KeyValueStore::set(repositorylocation or nil, key, value)
    KeyValueStore::getOrNull(repositorylocation or nil, key)
    KeyValueStore::getOrDefaultValue(repositorylocation or nil, key, defaultValue)
    KeyValueStore::destroy(repositorylocation or nil, key)
=end

require "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Catalyst/Runner.rb"
=begin 
    Runner::isRunning(uuid)
    Runner::runTimeInSecondsOrNull(uuid) # null | Float
    Runner::start(uuid)
    Runner::stop(uuid) # null | Float
=end

require "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Catalyst/Ping.rb"
=begin 
    Ping::put(uuid, weight)
    Ping::total24hours(uuid)
    Ping::totalToday(uuid)
=end

require "/Users/pascal/Galaxy/LucilleOS/Applications/Catalyst/Catalyst/Bank.rb"
=begin 
    Bank::put(uuid, weight)
    Bank::total(uuid)
=end

# --------------------------------------------------------------------

require_relative "Todo.rb"

# -----------------------------------------------------------------------------

def stop(uuid, item)
    timespan = Runner::stop(uuid)
    return if timespan.nil?
    timespan = [timespan, 3600*2].min # To avoid problems after leaving things running
    Items::itemReceivesRunTimespan(item, timespan, true)

    puts "Ping: putting #{timespan.round(2)} secs into catalyst measured times"
    Ping::put("DC9DF253-01B5-4EF8-88B1-CA0250096471", timespan)
end

if ARGV[0] == "start" and ARGV[1] then
    uuid = ARGV[1]
    exit if uuid.nil?
    item = Items::getOrNull(uuid)
    exit if item.nil?

    Runner::start(uuid)
    CatalystStandardTargets::openTarget(item["target"])

    if LucilleCore::askQuestionAnswerAsBoolean("-> done ? ", false) then
        stop(uuid, item)
        Items::destroy(item["uuid"])
        puts "Adding 1 to todo items done today"
        Ping::put("AEBAFC58-A70B-4623-A9C9-A00FF6BAAD0A", 1)
    else
        stop(uuid, item)
        if item["projectuuid"] == "44caf74675ceb79ba5cc13bafa102509369c2b53" then
            puts "Item was not immediately done, we need to classify it."
            Items::recast(item)
        end
    end
end

if ARGV[0] == "open" and ARGV[1] then
    uuid = ARGV[1]
    exit if uuid.nil?
    item = Items::getOrNull(uuid)
    exit if item.nil?

    CatalystStandardTargets::openTarget(item["target"])
end

if ARGV[0] == "stop" and ARGV[1] then
    uuid = ARGV[1]
    exit if uuid.nil?
    item = Items::getOrNull(uuid)
    exit if item.nil?

    stop(uuid, item)

    if item["projectuuid"] == "44caf74675ceb79ba5cc13bafa102509369c2b53" then
        puts "Item was not immediately done, we need to classify it."
        Items::recast(item)
    end
end

if ARGV[0] == "done" and ARGV[1] then
    uuid = ARGV[1]
    exit if uuid.nil?
    item = Items::getOrNull(uuid)
    exit if item.nil?

    stop(uuid, item)

    Items::destroy(item["uuid"])
    puts "Adding 1 to todo items done today"
    Ping::put("AEBAFC58-A70B-4623-A9C9-A00FF6BAAD0A", 1)
end

if ARGV[0] == "description" and ARGV[1] then
    uuid = ARGV[1]
    exit if uuid.nil?
    item = Items::getOrNull(uuid)
    exit if item.nil?

    item["description"] = CatalystCommon::editTextUsingTextmate(item["description"])
    Items::save(item)
end

if ARGV[0] == "recast" and ARGV[1] then
    uuid = ARGV[1]
    exit if uuid.nil?
    item = Items::getOrNull(uuid)
    exit if item.nil?

    Items::recast(item)
end

if ARGV[0] == "dive" and ARGV[1] then
    uuid = ARGV[1]
    exit if uuid.nil?
    item = Items::getOrNull(uuid)
    exit if item.nil?

    Items::diveItem(item)
end
