#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require 'json'
# JSON.pretty_generate(object)

require 'fileutils'
# FileUtils.mkpath '/a/b/c'
# FileUtils.cp(src, dst)
# FileUtils.mv 'oldname', 'newname'
# FileUtils.rm(path_to_image)
# FileUtils.rm_rf('dir/to/remove')

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/LucilleCore.rb"

# --------------------------------------------------------------------

require_relative "YouTubeVideoStream.rb"

# -----------------------------------------------------------------------------

if ARGV[0] == "view" then
    filepath = YouTubeVideoStream::videoFolderpathsAtFolder(YouTubeVideoStream::spaceFolderpath()).first
    return if filepath.nil?
    puts filepath
    if filepath.include?("'") then
        filepath2 = filepath.gsub("'", ',')
        FileUtils.mv(filepath, filepath2)
        filepath = filepath2
    end
    system("open '#{filepath}'")
    LucilleCore::pressEnterToContinue()
    FileUtils.rm(filepath)
    YouTubeVideoStream::registerHit()
end
