#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require 'json'
# JSON.pretty_generate(object)

require 'fileutils'
# FileUtils.mkpath '/a/b/c'
# FileUtils.cp(src, dst)
# FileUtils.mv 'oldname', 'newname'
# FileUtils.rm(path_to_image)
# FileUtils.rm_rf('dir/to/remove')

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/LucilleCore.rb"

require_relative "../Catalyst-Common/TwentyFourHoursCounterMetricHelper.rb"

require_relative "YouTubeVideoStream.rb"

# -----------------------------------------------------------------------------

if ARGV[0] == "play" then
    uuid = ARGV[1]
    exit if uuid.nil?
    filepath = YouTubeVideoStream::getVideoFilepathByUUIDOrNull(uuid)
    exit if filepath.nil?
    puts filepath
    if filepath.include?("'") then
        filepath2 = filepath.gsub("'", ',')
        FileUtils.mv(filepath, filepath2)
        filepath = filepath2
    end
    system("open '#{filepath}'")
    if LucilleCore::askQuestionAnswerAsBoolean("-> delete? ") then
        FileUtils.rm(filepath)
    end
    TwentyFourHoursCounterMetricHelper::ping("73718aae-ca1f-48b0-b6f5-10571e34b409")
end

if ARGV[0] == "delete" then
    uuid = ARGV[1]
    exit if uuid.nil?
    filepath = YouTubeVideoStream::getVideoFilepathByUUIDOrNull(uuid)
    exit if filepath.nil?
    puts filepath
    FileUtils.rm(filepath)
    TwentyFourHoursCounterMetricHelper::ping("73718aae-ca1f-48b0-b6f5-10571e34b409")
end
