#!/usr/bin/ruby

# encoding: UTF-8

require 'securerandom'
# SecureRandom.hex    #=> "eb693ec8252cd630102fd0d0fb7c3485"
# SecureRandom.hex(4) #=> "eb693123"
# SecureRandom.uuid   #=> "2d931510-d99f-494a-8c67-87feb05e1594"

require 'json'
# JSON.pretty_generate(object)

require 'colorize'

require_relative "../common/Code/LocalObjectsStore.rb"
require_relative "../common/Code/InfinityObjectsStore.rb"
require_relative "../common/Code/Genealogy.rb"
require_relative "../common/Code/CompositeElizabeth.rb"
require_relative "../common/Code/InfinityDriveDatablobsAndElizabeth.rb"
require_relative "../common/Code/XCacheDatablobsAndElizabeth.rb"
require_relative "../common/Code/LibrarianObjectsFileSystemCheck2.rb"
require_relative "../common/Code/Dx8UnitsUtils.rb"

# ------------------------------------------------------------------------------------

while (unitId = Mercury::readFirstValueOrNull("434BAAEC-EBA5-46AE-990E-85C86888A9D7")) do
    puts "Garbage collect Dx8Unit: #{unitId}"
    location = Dx8UnitsUtils::dx8UnitFolder(unitId)
    if File.exists?(location) then
        LucilleCore::removeFileSystemLocation(location)
        Mercury::dequeueFirstValueOrNull("434BAAEC-EBA5-46AE-990E-85C86888A9D7")
    else
        puts "(warning) cannot see location: #{location}. Aborting."
        exit
    end
end

