#!/usr/bin/ruby

# encoding: UTF-8

require 'securerandom'
# SecureRandom.hex    #=> "eb693ec8252cd630102fd0d0fb7c3485"
# SecureRandom.hex(4) #=> "eb693123"
# SecureRandom.uuid   #=> "2d931510-d99f-494a-8c67-87feb05e1594"

require 'json'
# JSON.pretty_generate(object)

require 'colorize'

require_relative "../common/Code/LocalObjectsStore.rb"
require_relative "../common/Code/EditionDesk.rb"
require_relative "../common/Code/Nx100s.rb"
require_relative "../common/Code/PrimitiveFiles.rb"
require_relative "../common/Code/Nx60s.rb"
require_relative "../common/Code/Dx8UnitsUtils.rb"

# ------------------------------------------------------------------------------------

EditionDesk::updateAndGarbageCollection()
