#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require_relative "InFlightControlSystem.rb"

# --------------------------------------------------------------------

def reportLineToContentItemLine(reportLine)
    if reportLine.include?("running") then
        "In Flight Control System 🛰️".green
    else
        "In Flight Control System 🛰️"
    end
end

def reportLineToContentItemBody(reportLine)
    reportLine.split(">>").join("\n>>")
end

objects = []
if flightControlIsActive() then
    reportLine = getReportLine()
    if reportLine then
        objects << {
            "uuid"           => SecureRandom.uuid,
            "contentItem"    => {
                "type" => "line-and-body",
                "line" => reportLineToContentItemLine(reportLine),
                "body" => reportLineToContentItemBody(reportLine)
            },
            "metric"         => 0.75,
            "commands"       => []
        }
    end
end
puts JSON.generate(objects)