#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require_relative "InFlightControlSystem.rb"

# --------------------------------------------------------------------

objects = []
if flightControlIsActive() then
    reportLine = getReportLine()
    if reportLine then
        objects << {
            "uuid"           => SecureRandom.uuid,
            "contentItem"    => {
                "type" => "line",
                "line" => reportLine
            },
            "metric"         => 0.75,
            "commands"       => []
        }
    end
end
puts JSON.generate(objects)