#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require_relative "InFlightControlSystem.rb"

# --------------------------------------------------------------------

items = getTopActiveItemsOrderedByTimespan()
            .select{|item| 
                getStartUnixtimeOrNull(item["uuid"]) and (Time.new.to_i - getStartUnixtimeOrNull(item["uuid"])) > 3600
            }
exit if items.empty?

onScreenNotification("ifcs", "#{items[0]["lucilleLocationBasename"]} is running for more than one hour")
