#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require 'json'
# JSON.pretty_generate(object)

require 'date'
require 'colorize'

require 'securerandom'
# SecureRandom.hex    #=> "eb693ec8252cd630102fd0d0fb7c3485"
# SecureRandom.hex(4) #=> "eb693123"
# SecureRandom.uuid   #=> "2d931510-d99f-494a-8c67-87feb05e1594"

require 'fileutils'
# FileUtils.mkpath '/a/b/c'
# FileUtils.cp(src, dst)
# FileUtils.mv 'oldname', 'newname'
# FileUtils.rm(path_to_image)
# FileUtils.rm_rf('dir/to/remove')

require 'digest/sha1'
# Digest::SHA1.hexdigest 'foo'
# Digest::SHA1.file(myFile).hexdigest

require 'find'

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/LucilleCore.rb"

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/KeyValueStore.rb"
=begin
    KeyValueStore::setFlagTrue(repositorylocation or nil, key)
    KeyValueStore::setFlagFalse(repositorylocation or nil, key)
    KeyValueStore::flagIsTrue(repositorylocation or nil, key)

    KeyValueStore::set(repositorylocation or nil, key, value)
    KeyValueStore::getOrNull(repositorylocation or nil, key)
    KeyValueStore::getOrDefaultValue(repositorylocation or nil, key, defaultValue)
    KeyValueStore::destroy(repositorylocation or nil, key)
=end

require_relative "InFlightControlSystem.rb"


# -------------------------------------------------------------------------

def printSummary()
    InFlightControlSystem::uuidsOrderedByPosition()
        .each{|uuid| puts InFlightControlSystem::itemToLongString(uuid) }
end

def selectUUIDOrNull()
    LucilleCore::selectEntityFromListOfEntitiesOrNull("item", InFlightControlSystem::uuidsOrderedByPosition(), lambda{|uuid| InFlightControlSystem::itemToLongString(uuid) })
end

loop {
    system("clear")
    uuid = selectUUIDOrNull()
    break if uuid.nil?
    puts ""
    operations = [
        "start item",
        "set description",
        "edit item contents",
        "destroy item"
    ]
    operation = LucilleCore::selectEntityFromListOfEntitiesOrNull("operation", operations)
    break if operation.nil?
    if operation == "start item" then
        InFlightControlSystem::start(uuid)
    end
    if operation == "set description" then
        text = InFlightControlSystem::getDescription(uuid)
        text = CatalystCommon::editTextUsingTextmate(text)
        InFlightControlSystem::setDescription(uuid, text)
    end
    if operation == "edit item contents" then
        InFlightControlSystem::editContent(uuid)
    end
    if operation == "destroy item" then
        if ["20200502-141331-226084", "20200502-141716-483780"].include?(uuid) then
            puts "Sorry Dave. You can't do that."
            LucilleCore::pressEnterToContinue()
            next
        end
        InFlightControlSystem::destroyItem(uuid)
    end
}
