#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require_relative "InFlightControlSystem.rb"

# --------------------------------------------------------------------

items = topItemsOrderedByTimespan()
            .select{|item| 
                companion = getCompanion(item["uuid"]) 
                companion["runningState"] and (Time.new.to_i - companion["runningState"]) > 3600
            }
exit if items.empty?

onScreenNotification("ifcs", "#{items[0]["description"]} is running for more than one hour")
