#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require_relative "InFlightControlSystem.rb"

# --------------------------------------------------------------------

nextaction = getNextAction()
nextaction[1].call()