#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require 'json'
# JSON.pretty_generate(object)

require 'date'
require 'colorize'

require 'securerandom'
# SecureRandom.hex    #=> "eb693ec8252cd630102fd0d0fb7c3485"
# SecureRandom.hex(4) #=> "eb693123"
# SecureRandom.uuid   #=> "2d931510-d99f-494a-8c67-87feb05e1594"

require 'fileutils'
# FileUtils.mkpath '/a/b/c'
# FileUtils.cp(src, dst)
# FileUtils.mv 'oldname', 'newname'
# FileUtils.rm(path_to_image)
# FileUtils.rm_rf('dir/to/remove')

require 'digest/sha1'
# Digest::SHA1.hexdigest 'foo'
# Digest::SHA1.file(myFile).hexdigest

require 'find'

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/LucilleCore.rb"

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/KeyValueStore.rb"
=begin
    KeyValueStore::setFlagTrue(repositorylocation or nil, key)
    KeyValueStore::setFlagFalse(repositorylocation or nil, key)
    KeyValueStore::flagIsTrue(repositorylocation or nil, key)

    KeyValueStore::set(repositorylocation or nil, key, value)
    KeyValueStore::getOrNull(repositorylocation or nil, key)
    KeyValueStore::getOrDefaultValue(repositorylocation or nil, key, defaultValue)
    KeyValueStore::destroy(repositorylocation or nil, key)
=end

require_relative "InFlightControlSystem.rb"


# -------------------------------------------------------------------------

def itemToString(uuid)
    runTime = InFlightControlSystem::runTimeInSecondsOrNull(uuid)
    runTimeAsString = runTime ? " (running for #{(runTime.to_f/3600).round(2)} hours)" : "" 
    ordinal = InFlightControlSystem::getCurrentOrdinalForUUIDOrNull(uuid)
    expectation = InFlightControlSystem::ordinalTo24HoursTimeExpectationInSeconds(ordinal)
    expectationString = if ["20200502-141331-226084", "20200502-141716-483780"].include?(uuid) then
                            "special circumstances"
                        else
                            "expect: #{"%6.3f" % (expectation.to_f/3600)} hours"
                        end
    "position: #{"%6.3f" % InFlightControlSystem::getPosition(uuid)} | ordinal: #{ordinal} | #{expectationString} | time: #{"%6.3f" % (InFlightControlSystem::storedTimespan(uuid).to_f/3600)} | metric: #{"%6.3f" % InFlightControlSystem::metric(uuid)} | #{InFlightControlSystem::getDescription(uuid)} #{runTimeAsString}"
end

def printSummary()
    InFlightControlSystem::uuidsOrderedByPosition()
        .each{|uuid| puts itemToString(uuid) }
end

def selectUUIDOrNull()
    LucilleCore::selectEntityFromListOfEntitiesOrNull("item", InFlightControlSystem::uuidsOrderedByPosition(), lambda{|uuid| itemToString(uuid) })
end

loop {
    system("clear")
    printSummary()
    puts ""
    operations = [
        "start item",
        "destroy item"
    ]
    operation = LucilleCore::selectEntityFromListOfEntitiesOrNull("operation", operations)
    break if operation.nil?
    if operation == "start item" then
        uuid = selectUUIDOrNull()
        next if uuid.nil?
        InFlightControlSystem::start(uuid)
    end
    if operation == "destroy item" then
        uuid = selectUUIDOrNull()
        next if uuid.nil?
        if ["20200502-141331-226084", "20200502-141716-483780"].include?(uuid) then
            puts "Sorry Dave. You can't do that."
            LucilleCore::pressEnterToContinue()
            next
        end
        InFlightControlSystem::destroyItem(uuid)
    end
}
