
# encoding: UTF-8

DATABANK_CATALYST_FOLDERPATH = "/Users/pascal/Galaxy/2020-DataBank/Catalyst"
CATALYST_BIN_TIMELINE_FOLDERPATH = "#{DATABANK_CATALYST_FOLDERPATH}/Bin-Timeline"
CATALYST_DATA_FOLDERPATH = "#{DATABANK_CATALYST_FOLDERPATH}/Data"

CATALYST_INBOX_STREAMUUID = "03b79978bcf7a712953c5543a9df9047"

