#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require 'json'
# JSON.pretty_generate(object)

require 'fileutils'
# FileUtils.mkpath '/a/b/c'
# FileUtils.cp(src, dst)
# FileUtils.mv 'oldname', 'newname'
# FileUtils.rm(path_to_image)
# FileUtils.rm_rf('dir/to/remove')

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/LucilleCore.rb"

# --------------------------------------------------------------------

require_relative "Anniversaries.rb"

# -----------------------------------------------------------------------------

if ARGV[0] == "activate" then
    Anniversaries::getNs1203WithOutstandingSequenceElements().each{|ns1203|
        ns1203["anniversaries"].each{|anniversary|
            puts ns1203["description"]
            puts JSON.pretty_generate(anniversary)
            LucilleCore::pressEnterToContinue()
            Anniversaries::markAnniversaryAsProcessed(ns1203, anniversary)
        }
    }
end
