#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Libs/loader.rb"

# ----------------------------------------------------------------------------

Thread.new {
    loop {
        sleep 3600
        system("#{File.dirname(__FILE__)}/vienna-import")
    }
}

Thread.new {
    require 'socket'                # Get sockets from stdlib
    server = TCPServer.open(2000)   # Socket to listen on port 2000
    loop {                          # Servers run forever
        Thread.start(server.accept) do |client|
            client.puts("Welcome to #{ENV["COMPUTERLUCILLENAME"]}")
            client.puts(Time.now.ctime) # Send the time to the client
            client.puts "Closing the connection. Bye!"
            client.close                # Disconnect from the client
        end
    }
}

Catalyst::program2()
