#!/Users/pascal/.rvm/rubies/ruby-2.5.1/bin/ruby

# encoding: UTF-8

require 'json'
# JSON.pretty_generate(object)

require 'fileutils'
# FileUtils.mkpath '/a/b/c'
# FileUtils.cp(src, dst)
# FileUtils.mv 'oldname', 'newname'
# FileUtils.rm(path_to_image)
# FileUtils.rm_rf('dir/to/remove')

require "/Users/pascal/Galaxy/LucilleOS/Software-Common/Ruby-Libraries/LucilleCore.rb"

# --------------------------------------------------------------------

require_relative "Wave.rb"

# -----------------------------------------------------------------------------

def openItem(claim)
    text = claim["description"]
    puts text
    if text.lines.to_a.size == 1 and text.start_with?("http") then
        url = text
        if NSXMiscUtils::isLucille18() then
            system("open '#{url}'")
        else
            system("open -na 'Google Chrome' --args --new-window '#{url}'")
        end
        return
    end
    if text.lines.to_a.size > 1 then
        LucilleCore::pressEnterToContinue()
        return
    end
end

if ARGV[0] == 'open' and ARGV[1] then
    uuid = ARGV[1]
    exit if uuid.nil?
    claim = WaveNextGen::getClaimByUUIDOrNUll(uuid)
    exit if claim.nil?
    openItem(uuid)
    exit
end

if ARGV[0] == 'open+done' and ARGV[1] then
    uuid = ARGV[1]
    exit if uuid.nil?
    claim = WaveNextGen::getClaimByUUIDOrNUll(uuid)
    exit if claim.nil?
    openItem(claim)
    NSXWaveUtils::performDone2(claim)
    exit
end

if ARGV[0] == 'done' and ARGV[1] then
    uuid = ARGV[1]
    exit if uuid.nil?
    claim = WaveNextGen::getClaimByUUIDOrNUll(uuid)
    exit if claim.nil?
    NSXWaveUtils::performDone2(claim)
    exit
end

if ARGV[0] == 'recast' and ARGV[1] then
    uuid = ARGV[1]
    exit if uuid.nil?
    claim = WaveNextGen::getClaimByUUIDOrNUll(uuid)
    exit if claim.nil?
    schedule = NSXWaveUtils::makeScheduleObjectInteractively()
    claim["schedule"] = schedule
    WaveNextGen::save(claim)
    exit
end

if ARGV[0] == 'description' and ARGV[1] then
    uuid = ARGV[1]
    exit if uuid.nil?
    claim = WaveNextGen::getClaimByUUIDOrNUll(uuid)
    exit if claim.nil?
    claim["description"] = CatalystCommon::editTextUsingTextmate(claim["description"])
    WaveNextGen::save(claim)
    exit
end

if ARGV[0] == 'destroy' and ARGV[1] then
    uuid = ARGV[1]
    exit if uuid.nil?
    claim = WaveNextGen::getClaimByUUIDOrNUll(uuid)
    exit if claim.nil?
    if LucilleCore::askQuestionAnswerAsBoolean("Do you want to destroy this item ? : ") then
        WaveNextGen::destroy(claim)
        exit
    end
    exit
end