
# encoding: UTF-8

DATABANK_FOLDER_PATH = "/Users/pascal/Galaxy/DataBank"
DATABANK_CATALYST_FOLDERPATH = "#{DATABANK_FOLDER_PATH}/Catalyst"
CATALYST_BIN_TIMELINE_FOLDERPATH = "#{DATABANK_CATALYST_FOLDERPATH}/Bin-Timeline"
CATALYST_DATA_FOLDERPATH = "#{DATABANK_CATALYST_FOLDERPATH}/Data"

CATALYST_INBOX_STREAMUUID = "03b79978bcf7a712953c5543a9df9047"

TODO_PATH_TO_DATA_FOLDER = "/Users/pascal/Galaxy/DataBank/Todo/Data"