
# encoding: UTF-8

CATALYST_COMMON_DATABANK_CATALYST_FOLDERPATH = "/Galaxy/DataBank/Catalyst"
CATALYST_COMMON_BIN_ARCHIVES_TIMELINE_FOLDERPATH = "#{CATALYST_COMMON_DATABANK_CATALYST_FOLDERPATH}/Bin-Timeline"
CATALYST_COMMON_TABLE_THROW_METRIC = 0.235711131 # https://en.wikipedia.org/wiki/Copeland–Erdős_constant
