
# encoding: UTF-8

CATALYST_COMMON_DATABANK_CATALYST_SHARED_FOLDERPATH = "/Galaxy/DataBank/Catalyst-Singleton"
CATALYST_COMMON_DATABANK_CATALYST_INSTANCE_FOLDERPATH = "/Galaxy/DataBank/Catalyst-#{ENV["COMPUTERLUCILLENAME"]}"
CATALYST_COMMON_BIN_ARCHIVES_TIMELINE_FOLDERPATH = "#{CATALYST_COMMON_DATABANK_CATALYST_SHARED_FOLDERPATH}/Bin-Timeline"
